- .env.template
- .github-labelsrc.json
- package.json
- yarn.lock
FYI: labels have been applied already and are the same as the ones in app-kit.
This is a tool [we wrote](https://github.com/commercetools/github-labels/) to help manage the github labels as a config file.
> chore: setup github labels

- .stylelintignore
- .stylelintrc
- jest.stylelint.config.js
- package.json
- yarn.lock
This is useful to lint css-in-js.
Reference implementation: https://github.com/commercetools/ui-kit/pull/815
> chore: setup stylelint

- husky.config.js
- lint-staged.config.js
- package.json
- yarn.lock
This runs on the `pre-commit` hook. For now it's only about formatting and linting.
> chore: setup lint-staged

- websites/docs-smoke-test/gatsby-config.js
- websites/docs-smoke-test/src/content/code-samples/code-block.mdx
- websites/docs-smoke-test/src/content/code-samples/code-with-line-highlight.mdx
- websites/docs-smoke-test/src/content/code-samples/code-with-title.mdx
- websites/docs-smoke-test/src/content/code-samples/inline-code.mdx
- websites/docs-smoke-test/src/content/code-samples/multi-language-code.mdx
- websites/docs-smoke-test/src/content/custom-elements/info-boxes.mdx
- websites/docs-smoke-test/src/content/images/image-with-caption.mdx
- websites/docs-smoke-test/src/content/images/image.mdx
- websites/docs-smoke-test/src/content/images/inline-image.mdx
- websites/docs-smoke-test/src/content/images/svg-image.mdx
- websites/docs-smoke-test/src/content/images/tall-image.mdx
- websites/docs-smoke-test/src/content/images/transparent-image.mdx
- websites/docs-smoke-test/src/content/index.mdx
- websites/docs-smoke-test/src/content/smoke-tests/blockquotes.mdx
- websites/docs-smoke-test/src/content/smoke-tests/definition-lists.mdx
- websites/docs-smoke-test/src/content/smoke-tests/empty-page.mdx
- websites/docs-smoke-test/src/content/smoke-tests/horizontal-rule.mdx
- websites/docs-smoke-test/src/content/smoke-tests/lead-section.mdx
- websites/docs-smoke-test/src/content/smoke-tests/links.mdx
- websites/docs-smoke-test/src/content/smoke-tests/lists.mdx
- websites/docs-smoke-test/src/content/smoke-tests/page-with-little-content.mdx
- websites/docs-smoke-test/src/content/smoke-tests/right-nav-submenu.mdx
- websites/docs-smoke-test/src/content/smoke-tests/table.mdx
- websites/docs-smoke-test/src/content/smoke-tests/text.mdx
> refactor(theme): remove unused shortTitle from frontmatter

- packages/gatsby-theme-docs/src/layouts/internals/globals.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
- packages/gatsby-theme-docs/src/layouts/internals/page-navigation.spec.js
> fix(theme): prefer overflow: auto

- packages/gatsby-theme-docs/gatsby-ssr.js
> feat(theme): setup cookie consent script

- .gitignore
These don't work for me:
```
-.vscode
-!.vscode/settings.json
```
> chore: git ignore all in vscode except settings

- packages/gatsby-theme-docs/package.json
- packages/gatsby-theme-docs/src/components/markdown.js
- packages/gatsby-theme-docs/src/layouts/internals/globals.js
- packages/gatsby-theme-docs/src/utils/code-block-parse-options.js
- websites/docs-smoke-test/src/content/views/code-blocks.mdx
- yarn.lock
> refactor(code-block): to support title infostring

- packages/gatsby-theme-docs/src/layouts/content.js
Just to get a deploy link for now...
> refactor(theme): use left-aligned layout

- packages/gatsby-theme-docs/gatsby-node.js
- websites/docs-smoke-test/src/content/components/images.mdx
> refactor(theme): to support absolute imports

- packages/broken-link-checker/broken-link-checker.js
> fix(broken-link-checker): typo

- packages/gatsby-theme-docs/src/components/markdown.js
- packages/gatsby-theme-docs/src/templates/page-content.js
- websites/docs-smoke-test/src/content/index.mdx
> feat(theme): style definition list elements

- packages/gatsby-theme-docs/src/components/content-pagination.js
I previously assumed that page files are grouped into folders based on the chapter. However, page files structure should not directly depend on the navigation links.
This PR refactors the links matching for the pagination links to pick all chapter links as soon as the page slug matches one of the links in the chapter.
> fix(theme): match chapter links also for flat page structure

- websites/api-docs-smoke-test/src/api-specs/test/api.raml
- websites/api-docs-smoke-test/src/api-specs/test/examples/example-nonconforming.json
- websites/api-docs-smoke-test/src/api-specs/test/examples/example.json
Copy of test API specs based on @nkuehn improvements in this branch:
https://github.com/commercetools/commercetools-docs-kit/tree/exploration-of-new-raml-parser-wale
> feat: test api specs

- packages/broken-link-checker/bin/broken-link-checker.js
> fix(broken-link-checker): merging options

- packages/gatsby-theme-docs/src/layouts/internals/layout-centered.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
See https://caniuse.com/#search=overflow
> fix(theme): overflow shorthand

- packages/broken-link-checker/src/run.js
> feat(broken-link-checker): warn on insecure links

- packages/gatsby-theme-docs/index.js
- packages/ui-kit/README.md
Leftovers from the previous release
> fix(theme): missing exports, add README to uikit

- cypress/integration/docs-smoke-test/menu-navigation.js
- packages/gatsby-theme-docs/src/components/index.js
- packages/gatsby-theme-docs/src/components/overlay.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
Just an internal refactoring to have a bit more consistency and to render overlay elements into a specific DOM container using react portal.
> refactor(theme): to render navigation overlays into a portal

- packages/gatsby-theme-api-docs/package.json
- packages/gatsby-theme-api-docs/src/components/api/resource-method.js
- packages/gatsby-theme-api-docs/src/components/api/resource/method/method.js
- packages/gatsby-theme-api-docs/src/components/api/resource/method/parameters.js
- packages/gatsby-theme-api-docs/src/components/api/resource/method/url-scopes-responses/responses.js
- packages/gatsby-theme-api-docs/src/components/api/resource/method/url-scopes-responses/scopes.js
- packages/gatsby-theme-api-docs/src/components/api/resource/method/url-scopes-responses/title.js
- packages/gatsby-theme-api-docs/src/components/api/resource/method/url-scopes-responses/url-scopes-responses.js
- packages/gatsby-theme-api-docs/src/components/api/resource/resource.js
- packages/gatsby-theme-api-docs/src/components/api/table.js
- packages/gatsby-theme-api-docs/src/design-system.js
- packages/gatsby-theme-api-docs/src/hooks/use-read-resource-by-resource-path.js
This the implementation of the [design](https://commercetools.invisionapp.com/d/main?origin=v7#/console/17784193/388243826/preview?scrollOffset=946) for a resource method.
Closes https://github.com/commercetools/commercetools-docs-kit/pull/210
> Method design implementation

- .circleci/config.yml
- cypress/integration/docs-smoke-test/top-menu.js
- packages/gatsby-theme-docs/gatsby-config.js
- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-theme-docs/src/components/index.js
- packages/gatsby-theme-docs/src/components/top-menu.js
- packages/gatsby-theme-docs/src/data/top-menu.yaml
- packages/gatsby-theme-docs/src/data/top-side-menu.yaml
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
- websites/docs-smoke-test/gatsby-config.js
> feat(theme): implement top menu for global links

- packages/gatsby-theme-api-docs/src/components/required.js
- packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
- packages/gatsby-theme-api-docs/src/components/resource/method/url-scopes-responses/url-scopes-responses.js
- packages/gatsby-theme-api-docs/src/components/table.js
- packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
- packages/gatsby-theme-api-docs/src/design-system.js
Implementation of things I previously missed in the design [here](https://commercetools.invisionapp.com/d/main?origin=v7#/console/17784193/388243826/preview?scrollOffset=39):
- property name and type styling (`name-type.js`)
- Resource url styling (`url-scopes-responses.js`)
> Resource design implementation

- CHANGELOG.md
- packages/gatsby-theme-docs/README.md
- packages/writing-style/vale-styles/commercetools/Brand.yml
- packages/writing-style/vale-styles/commercetools/Product.yml
> fix(writing-style): mapping of custom apps casing

- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
> fix(theme): sidebar link border color

- packages/gatsby-theme-docs/gatsby-ssr.js
The initial fix in #265 didn't work for all cases. This should do the trick.
> fix(theme): to use correct selector to exclude style elements

- packages/gatsby-theme-api-docs/src/hooks/use-api-resources.js
- packages/gatsby-transformer-raml/gatsby-node.js
- packages/gatsby-transformer-raml/src/schema/define-raml-resource.js
Closes https://github.com/commercetools/commercetools-docs-kit/issues/264
> refactor: enhanced graphql for resources

- .circleci/config.yml
- .github/workflows/main.yml
- scripts/release_canary.sh
Read motivation here: https://github.com/commercetools/commercetools-docs-kit/pull/209#issuecomment-576024614
TL;DR: remove CircleCI and use GitHub Actions to run the CI workflow.
> chore: try CI workflow with github actions

- .github/workflows/main.yml
- package.json
> refactor(actions): include canary release in main workflow

- packages/gatsby-theme-docs/src/hooks/use-active-section.js
- packages/gatsby-theme-docs/src/hooks/use-scroll-position.js
- packages/gatsby-theme-docs/src/hooks/use-scroll-spy.js
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
Closes #38 
Tests might follow up, I need to think how we can test this properly.
> feat(theme): restore scroll position of main navigation links, when navigating to a new page

- packages/gatsby-theme-docs/gatsby-config.js
> fix(theme): remove duplicated source filesystem config

- packages/gatsby-transformer-mdx-introspection/gatsby-node.js
Fixes https://github.com/commercetools/commercetools-docs-kit/issues/263
> fix: appropriate async implementation for gatsby

- .gitignore
- packages/gatsby-theme-docs/README.md
- packages/gatsby-theme-docs/gatsby-browser.js
- packages/gatsby-theme-docs/gatsby-config.js
- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-theme-docs/package.json
- packages/ui-kit/src/components/multi-code-block.js
- websites/docs-smoke-test/gatsby-config.js
- websites/docs-smoke-test/src/code-examples/example.scala
- websites/docs-smoke-test/src/content/components/code-examples.mdx
- yarn.lock
See https://github.com/facebook/docusaurus/pull/2250
> feat(theme): add support for specifying new languages for Prism

- packages/writing-style/.vale.ini
- packages/writing-style/vale-styles/commercetools/Acronyms.yml
- packages/writing-style/vale-styles/commercetools/Weasel.yml
- packages/writing-style/vale-styles/commercetools/WordList.yml
* no content in html and txt files any more - prevents the checker from running over the built html output if called from a repo root
* some tuning (learnt from the current docs content)
> feat(writing-style): finishing to get the current docs content ready

- packages/writing-style/.vale.ini
- packages/writing-style/vale-styles/commercetools/Acronyms.yml
- packages/writing-style/vale-styles/commercetools/Units.yml
- packages/writing-style/vale-styles/commercetools/WordList.yml
Final tuning after Adina did the "mega-chore" job of fixing all the writing style objections in the complete existing documentation body.
> feat(writing-style): cover the last few cases from the existing docs

- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-theme-docs/src/layouts/release-notes.js
- packages/gatsby-theme-docs/src/templates/releases.js
- websites/docs-smoke-test/src/content/releases.mdx
- websites/docs-smoke-test/src/releases/release-format-definition.mdx
> refactor(theme): to keep the minimum setup for release notes

- packages/gatsby-theme-api-docs/src/components/resource/method/method.js
- packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
- packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
- packages/gatsby-theme-api-docs/src/utils/generate-type-to-render.js
- websites/api-docs-smoke-test/source-raml/test/api.raml
- websites/api-docs-smoke-test/src/api-specs/test/gen.properties
- websites/api-docs-smoke-test/src/api-specs/test/resources/ByProjectKeyResource.raml
> fix: query parameters types that are objects now render as links

- packages/gatsby-theme-docs/gatsby-browser.js
> fix(theme): remove check for zeit github branch

- packages/gatsby-theme-docs/src/layouts/internals/layout-release-note.js
- packages/gatsby-theme-docs/src/templates/release-notes-list.js
- packages/ui-kit/src/design-system.js
Implementation of this [design](https://commercetools.invisionapp.com/d/main?origin=v7#/console/19438556/408192223/preview?scrollOffset=215)
> Release notes list design implementation

- packages/gatsby-theme-docs/src/components/release-notes-subscribe-links.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-release-notes-filters.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-release-note.js
see https://github.com/commercetools/commercetools-docs-kit/issues/314#issuecomment-613382600
> refactor: release notes left over

- package.json
- packages/gatsby-theme-docs/package.json
- packages/gatsby-theme-docs/src/layouts/internals/layout-release-note.js
- yarn.lock
Follow up of #355 to use emotion theming to customize the "fix" tone styles.
> refactor(theme): to customize Stamp using theme

- packages/gatsby-theme-docs/src/components/release-notes-subscribe-links.js
- packages/gatsby-theme-docs/src/icons/rss.svg
- packages/ui-kit/src/design-system.js
Closes #362 
Design: https://commercetools.invisionapp.com/d/main?origin=v7#/console/19438556/408192223/preview?scrollOffset=215
> feat: release notes link to rss and product newsletter

- packages/gatsby-theme-docs/src/components/release-notes-subscribe-links.js
> fix(theme): rss link to be treated as external link

- packages/gatsby-theme-docs/src/components/release-notes-subscribe-links.js
- packages/gatsby-theme-docs/src/templates/release-notes-list.js
- packages/gatsby-theme-docs/src/utils/markdown-fragment-to-react.js
- packages/ui-kit/src/components/markdown.js
- websites/docs-smoke-test/src/releases/excerpt-rendering-test.mdx
> fix(theme): proptype warnings and mapping of some md elements

- .github/workflows/main.yml
- package.json
- yarn.lock
To avoid installing Cypress and deps multiple times.
https://github.com/marketplace/actions/cypress-io#custom-install
> refactor(ci): to not use cypress github action

- packages/gatsby-transformer-raml/src/create-type-node.js
> fix: stop rendering deprecated properties

- packages/gatsby-theme-docs/README.md
- packages/gatsby-theme-docs/gatsby-config.js
> feat(theme): allow to override top-menu links

- packages/gatsby-theme-docs/README.md
- packages/gatsby-theme-docs/default-options.js
- packages/gatsby-theme-docs/gatsby-config.js
- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
- packages/gatsby-theme-docs/src/layouts/release-notes-detail.js
- packages/gatsby-theme-docs/src/layouts/release-notes-list.js
- packages/gatsby-theme-docs/src/templates/page-content.js
- packages/gatsby-theme-docs/src/templates/release-notes-detail.js
- packages/gatsby-theme-docs/src/templates/release-notes-list.js
- packages/ui-kit/src/components/markdown.js
- packages/ui-kit/src/design-system.js
- websites/api-docs-smoke-test/gatsby-config.js
> feat(theme): allow to configure website primary color

- packages/gatsby-theme-docs/src/components/seo.js
> fix: element keys should be unique

- .changeset/new-kangaroos-smell.md
- cypress/integration/docs-smoke-test/pagination.js
- packages/gatsby-theme-code-examples/src/code-example.js
- packages/gatsby-theme-code-examples/src/multi-code-example.js
- packages/ui-kit/src/components/code-block.js
- packages/ui-kit/src/components/multi-code-block.js
- packages/ui-kit/src/design-system.js
- packages/ui-kit/src/prism-themes/commercetools.js
- packages/ui-kit/src/utils/code-block-parse-options.js
- websites/docs-smoke-test/src/content/components/code-blocks.mdx
- websites/docs-smoke-test/src/content/components/code-examples.mdx
- websites/docs-smoke-test/src/content/views/code-examples.mdx
- websites/docs-smoke-test/src/data/navigation.yaml
> feat(theme): use primary/secondary versions of prism themes for code blocks

- .changeset/quiet-impalas-fly.md
- packages/ui-kit/src/components/markdown.js
Closes https://github.com/commercetools/commercetools-docs-kit/issues/453
> fix: remove custom word spacing

- .changeset/honest-crews-boil.md
- packages/gatsby-theme-api-docs/src/components/type/children-union-like.js
- packages/gatsby-theme-api-docs/src/components/type/children.js
- packages/gatsby-theme-api-docs/src/components/type/examples.js
- packages/gatsby-theme-api-docs/src/components/type/type.js
Closes https://github.com/commercetools/commercetools-docs-kit/issues/450
> refactor: render api type examples with title

- .changeset/dry-houses-worry.md
- packages/ui-kit/src/components/code-block.js
- packages/ui-kit/src/design-system.js
- websites/docs-smoke-test/src/content/components/code-blocks.mdx
> fix(theme): use correct theme prop for code blocks

- .changeset/late-queens-drum.md
- packages/ui-kit/src/components/rss-feeds.js
- websites/docs-smoke-test/src/content/components/rss-feeds.mdx
Closes https://github.com/commercetools/commercetools-docs-kit/issues/515
> rss feeds with custom title

- packages/gatsby-theme-api-docs/src/components/type/examples.js
Closes https://github.com/commercetools/commercetools-docs-kit/issues/527
> refactor: if example name is "default" do not render it

- .changeset/weak-trains-whisper.md
- packages/gatsby-theme-docs/src/components/top-menu.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
Closes https://github.com/commercetools/commercetools-docs-kit/issues/538
> feat: option to center top menu

- .changeset/unlucky-adults-cross.md
- packages/gatsby-theme-docs/src/components/side-by-side.js
Fixes build fail in https://github.com/commercetools/commercetools-docs/pull/418
> fix: improper import

- .changeset/little-days-smell.md
- packages/gatsby-theme-api-docs/src/components/type/enum.js
Fix for build failure in https://github.com/commercetools/commercetools-docs/pull/422.
See comment - https://github.com/commercetools/commercetools-docs/pull/422#issuecomment-656526780
> fix: undefined enum description that causes build failure

- .changeset/wise-tigers-lick.md
- packages/gatsby-transformer-raml/src/schema/define-raml-resource.js
- packages/gatsby-transformer-raml/src/utils/resource/code-examples-to-array.js
- packages/gatsby-transformer-raml/src/utils/resource/code-examples-to-array.spec.js
- packages/gatsby-transformer-raml/src/utils/resource/do-recursion.js
- packages/gatsby-transformer-raml/src/utils/resource/process-methods.js
Second of 3 parts PR for https://github.com/commercetools/commercetools-docs-kit/issues/445
> refactor: transform api code examples

- .changeset/metal-ladybugs-eat.md
- packages/ui-kit/src/components/multi-code-block.js
> refactor: spacing in code example title bar

- .changeset/thirty-ears-call.md
- packages/gatsby-theme-docs/src/components/content-pagination.js
> refactor: align nav-buttons in wide layout into the middle

- .changeset/lovely-suits-judge.md
- packages/ui-kit/src/components/rss-feeds.js
- packages/ui-kit/src/design-system.js
- packages/writing-style/.gitignore
> fix: add fixed date column width in RSS feed

- .changeset/thick-books-sparkle.md
- packages/gatsby-theme-docs/src/components/algolia-search.js
> fix: space between search result entries

- .changeset/config.json
- package.json
- yarn.lock
See https://github.com/atlassian/changesets/pull/458
> refactor(changeset): use globs for linked packages

- .changeset/mean-ways-clean.md
- packages/ui-kit/src/design-system.js
Closes https://github.com/commercetools/commercetools-docs-kit/issues/712
> refactor: New color for light themed header code block

- .changeset/nice-socks-lay.md
- linkinator.config.json
- packages/gatsby-theme-docs/src/data/top-menu.yaml
- packages/gatsby-theme-docs/src/data/top-side-menu.yaml
Closes https://github.com/commercetools/commercetools-docs-kit/issues/707
> refactor: update top menu

- .changeset/nasty-houses-mate.md
- packages/ui-kit/src/components/markdown.js
- websites/docs-smoke-test/src/content/views/markdown.mdx
> refactor: add full width to tables in body column

- .changeset/perfect-drinks-rescue.md
- packages/gatsby-theme-docs/gatsby-browser.js
- packages/gatsby-theme-docs/package.json
- yarn.lock
> fix(theme): load polyfill for IntersectionObserver API, when necessary

- .changeset/calm-bulldogs-repair.md
- jest.text.config.js
- packages/gatsby-theme-docs/gatsby-config.js
- packages/ui-kit/src/components/rss-feed-table.js
- packages/ui-kit/src/components/rss-feeds.js
- packages/ui-kit/src/components/rss-feeds.spec.js
- packages/ui-kit/src/design-system.js
- packages/ui-kit/src/index.js
- websites/docs-smoke-test/src/content/components/rss-feeds.mdx
- yarn.lock
resolves #722 
**Hints for review**
- After thinking it over again, I decided to pass the feed url over props to the component. I think it makes more sense than to wrap the feeds with a parent component.
- I seperated the logic into two components called `RssFeed` which handles the requests and refactores the data, and `RssFeedTable` which gets the data from `RssFeed` and simply puts them into the table
> refactor: restructure rss feed table

- .changeset/perfect-trainers-thank.md
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-header-side.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page.js
> fix: remove width overrides in right column

- .changeset/rude-apes-share.md
- websites/api-docs-smoke-test/src/releases/test-release-note-one.mdx
- websites/api-docs-smoke-test/src/releases/test-release-note-two.mdx
- websites/docs-smoke-test/src/content/components/rss-feeds.mdx
> refactor: change datasource of rss feeds in smoke-test

- package.json
- yarn.lock
Follow up of #809 given that they released a fix.
> chore: update linkinator to 2.11.2

- .changeset/spicy-knives-give.md
- packages/gatsby-theme-docs/src/components/child-sections-nav.js
- websites/docs-smoke-test/src/content/components/child-section-navigation.mdx
> fix: size of grey hovering area in child section nav

- .changeset/slow-ants-tie.md
- packages/gatsby-theme-docs/bin/create-release-note
- packages/gatsby-theme-docs/bin/create-release-note.js
- packages/gatsby-theme-docs/package.json
- yarn.lock
closes #723 
Note: pls check if the output has the correct format and if it matches the requirements. Thanks.
> feat: script for generating release note files

- .changeset/rare-dragons-worry.md
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
- packages/ui-kit/src/design-system.js
This was already discussed with @Shecki 
closes #846
> align arrowUpIcon to page title

- .changeset/ten-humans-arrive.md
- packages/ui-kit/src/components/markdown.js
> fix: remove top margin on first content element

- .changeset/tame-cougars-join.md
- packages/gatsby-theme-docs/src/components/child-sections-nav.js
- packages/gatsby-theme-docs/src/components/overlay.js
- packages/gatsby-theme-docs/src/components/search-input.js
- packages/gatsby-theme-docs/src/components/top-menu.js
- packages/gatsby-theme-docs/src/layouts/content-homepage.js
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-header-logo.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-wrapper.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
- packages/gatsby-theme-docs/src/layouts/release-notes-detail.js
- packages/gatsby-theme-docs/src/layouts/release-notes-list.js
- packages/ui-kit/src/components/media-query.js
- packages/ui-kit/src/design-system.js
closes #564 
Note: Pls let me know what you think about the duration of the animation. For the left and right bar we use 0.5sec at the moment.
> feat: add opening animation to top menu

- .changeset/blue-gorillas-agree.md
- packages/gatsby-theme-docs/src/components/child-sections-nav.js
- packages/gatsby-theme-docs/src/components/search-dialog.js
- packages/gatsby-theme-docs/src/components/search-input.js
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
- packages/ui-kit/src/components/media-query.js
- packages/ui-kit/src/design-system.js
> Move searchbox over index nav

- .changeset/nasty-items-rule.md
- packages/rmf-codegen/package.json
From #914 , so that Percy can run properly (as the original PR was from a fork).
> chore(deps): bump codegen (#914)

- .changeset/selfish-ties-yell.md
- packages/rmf-codegen/package.json
codegen update for annotation support at api root & security scheme level e.g. for the different baseUris.
> chore(deps): update codegen to 0.1.5

- .changeset/slimy-lizards-brush.md
- api-specs/test/annotation-types/annotations.raml
- api-specs/test/api.raml
- packages/rmf-codegen/package.json
updates the codegen to have the ability to override the baseUri by using an annotation
> chore(deps): update codegen to 0.1.7

- .changeset/sharp-tomatoes-hammer.md
- packages/gatsby-theme-api-docs/src/components/resource/method/method.js
> refactor: lowercase 'parameters'

- .changeset/cool-llamas-change.md
- packages/gatsby-theme-docs/src/components/top-menu.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-release-notes-filters.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
> Use same animation transition for all animations

- .changeset/eighty-pianos-ring.md
- packages/gatsby-theme-docs/src/components/search-dialog.js
> Animate search dialog

- .changeset/soft-moose-nail.md
- api-specs/test/types/regex-properties-type.raml
- packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
- websites/api-docs-smoke-test/src/content/types/general.mdx
> Visualize regex properties

- .changeset/pretty-crabs-glow.md
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-release-notes-filters.js
> Use unique IDs for search-inputs

- .changeset/hungry-rules-lick.md
- packages/gatsby-theme-api-docs/src/hooks/use-type-locations.js
> refactor: type location overrides

- .changeset/hot-ravens-occur.md
- packages/gatsby-theme-api-docs/src/hooks/use-type-locations.js
> refactor: type-locations hook to improve performance

- .changeset/thirty-plants-double.md
- packages/gatsby-theme-docs/src/components/child-sections-nav.js
- websites/docs-smoke-test/src/content/components/child-section-navigation.mdx
> fix: duplicate searchInput id

- .changeset/ao-fix-property-name-beta-spacing-v2.md
- api-specs/test/types/annotations-test-type.raml
- packages/gatsby-theme-api-docs/src/components/required.js
- packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
- packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
> fix: property name and beta flag spacing

- .changeset/strange-parents-remain.md
- packages/gatsby-theme-docs/gatsby-browser.js
- packages/gatsby-theme-docs/src/components/search-input.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
- packages/ui-kit/src/components/globals.js
- yarn.lock
> fix: issue with tabIndex for keyboard navigation

- .changeset/four-readers-swim.md
- packages/gatsby-theme-docs/src/components/child-sections-nav.js
> fix: avoid page breaking inside for firefox

- .changeset/chilly-turtles-grow.md
- api-specs/test/types/enums.raml
- packages/gatsby-theme-api-docs/src/components/type/enum.js
> feat: parse enum description as markdown

- .changeset/gatsby-transformer-raml-sort-query-params.md
- api-specs/test/api.raml
- packages/gatsby-theme-api-docs/README.md
- packages/gatsby-transformer-raml/README.md
- packages/gatsby-transformer-raml/gatsby-node.js
- packages/gatsby-transformer-raml/src/create-resource-node.js
- packages/gatsby-transformer-raml/src/create-type-node.js
- packages/gatsby-transformer-raml/src/utils/resource/process-methods.js
- packages/gatsby-transformer-raml/src/utils/sort-properties.js
- packages/gatsby-transformer-raml/src/utils/sort-properties.spec.js
- websites/api-docs-smoke-test/gatsby-config.js
- websites/api-docs-smoke-test/src/content/endpoints/methods.mdx
> feat(gatbsy-transformer-raml): moveEndpointQueryParametersToTop & moveEndpointQueryParametersToBottom config options

- .changeset/good-dingos-search.md
- packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
> Don't render a dash when parameter has no description

- api-specs/test/package.json
- yarn.lock
This will fix the problem in [this](https://github.com/commercetools/commercetools-docs-kit/pull/1161) PR.
> Update rmf-codegen for api-specs/test

- .changeset/orange-jars-teach.md
- api-specs/test/types/regex-properties-type.raml
- packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
- packages/gatsby-theme-api-docs/src/components/type/properties/regex-properties.js
- packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
- packages/gatsby-theme-api-docs/src/utils/render-regex-property.js
> Implement formatting for regex in query parameters

- packages/gatsby-theme-docs/package.json
- packages/ui-kit/package.json
- websites/docs-smoke-test/package.json
Follow up of #1165 
See https://react-svgr.com/docs/cli/
> fix: svgr command

- .changeset/hungry-panthers-heal.md
- packages/gatsby-theme-docs/src/templates/homepage.js
- packages/gatsby-theme-docs/src/templates/page-content.js
> fix: missing graphql query field

- .changeset/shiny-melons-retire.md
- packages/gatsby-theme-docs/src/components/release-notes-filter-topics.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-release-notes-filters.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
- websites/docs-smoke-test/src/releases/release-format-definition.mdx
closes #1100 
Link to the preview:
https://commercetools-docs-kit-eqh3nb76b-commercetools.vercel.app/docs-smoke-test/releases
> Fix scrolling through release note topics

- .changeset/ten-camels-enjoy.md
- packages/gatsby-theme-docs/src/components/child-sections-nav.js
- websites/docs-smoke-test/src/content/components/child-section-navigation.mdx
- websites/documentation/src/content/writing/navigation.mdx
> Implement subsection support in child-section-nav

- .changeset/cool-carrots-push.md
- packages/writing-style/styles/commercetools/Product.yml
> Apply writing style improvements

- .changeset/wicked-parents-mate.md
- packages/gatsby-theme-docs/src/components/release-notes-filter-dates.js
- packages/gatsby-theme-docs/src/components/release-notes-filter-topics.js
> Lowercase section headings in release note filter

- .changeset/wet-rockets-fetch.md
- packages/writing-style/styles/commercetools/DiscriminatoryWords.yml
resolves the issue we discussed here:
https://github.com/commercetools/merchant-center-application-kit/pull/2561#discussion_r854576394
> Add `native Merchant Center application` as writing style exception

- .changeset/young-students-wait.md
- packages/gatsby-theme-api-docs/src/utils/transform-urn-links-plugin.js
> fix(plugin): improve error handling and message

- websites/docs-smoke-test/gatsby-config.js
- websites/docs-smoke-test/src/content/components/quiz.mdx
closes https://github.com/commercetools/learning-tech/issues/196
> [Self-learning] configure learning plugin with addOns

- .changeset/rotten-ducks-flash.md
- packages/ui-kit/src/utils/css-variables.spec.ts
- packages/ui-kit/src/utils/css-variables.ts
Fixing small regression from #1372 
Fixes #1384
> fix(uikit): extracting CSS color values

- .changeset/perfect-mirrors-worry.md
- .github/workflows/main.yml
- packages/gatsby-theme-docs/src/templates/homepage.js
- packages/gatsby-theme-docs/src/templates/page-content.js
- packages/gatsby-theme-docs/src/templates/release-notes-detail.js
- packages/gatsby-theme-docs/src/templates/release-notes-list.js
Attempt to fix an error happening during `docs` repo upgrade.
https://github.com/gatsbyjs/gatsby/discussions/25068#discussioncomment-3105104
> fix(mdx2): using named queries generate errors

- cypress/e2e/docs-smoke-test/learn-api/login.ts
- cypress/e2e/docs-smoke-test/learn-api/quiz.ts
- cypress/support/step_definitions/common.steps.ts
- package.json
- yarn.lock
Address https://github.com/commercetools/commercetools-docs-kit/pull/1579
> chore: upgrade @badeball/cypress-cucumber-preprocessor to v15

- .changeset/great-guests-attack.md
- api-specs/test/annotation-types/annotations.raml
- api-specs/test/types/enums.raml
- packages/gatsby-theme-api-docs/src/components/type/enum.js
- packages/gatsby-theme-api-docs/src/components/type/type.js
- packages/gatsby-theme-api-docs/src/hooks/use-api-types.js
- packages/gatsby-transformer-raml/src/create-type-node.mjs
- packages/gatsby-transformer-raml/src/schema/define-raml-type.mjs
- websites/api-docs-smoke-test/src/content/types/enums-constants-unions.mdx
closes #1539 
See proposals here:
https://github.com/commercetools/commercetools-docs/pull/3047
I decided to implement Stefans proposal here:
https://github.com/commercetools/commercetools-docs/pull/3047#issuecomment-1481509904
Nikolaus proposal was not working with the current ramldoc generator version, unfortunately.
> [New Feature] Introduce enum grouping

- .changeset/fifty-melons-fry.md
- packages/gatsby-theme-sso-ui-kit/README.md
- packages/gatsby-theme-sso-ui-kit/gatsby-browser.js
- packages/gatsby-theme-sso-ui-kit/gatsby-node.mjs
- packages/gatsby-theme-sso-ui-kit/src/components/config-context.ts
- packages/gatsby-theme-sso-ui-kit/src/components/login-component.spec.tsx
- websites/docs-smoke-test/gatsby-config.mjs
- websites/documentation/gatsby-config.mjs
- websites/documentation/src/content/configuration/sso.mdx
part of #1615 
Sorry, I was too fast with the new PR 😅 
But we can merge it into the other pull request. It's also easier for you to review this way :)
> Toggle login/logout buttons over the `hideLogin` flag in the sso plugin config

- .changeset/angry-maps-nail.md
> docs: add missing changeset

- .changeset/moody-crabs-end.md
- packages/gatsby-theme-learning/README.md
- packages/gatsby-theme-learning/shortcodes.js
- packages/gatsby-theme-learning/src/components/first-name.tsx
- packages/gatsby-theme-learning/src/index.ts
- websites/docs-smoke-test/src/content/self-learning/overview.mdx
> Implement `FirstName` component

- .changeset/hot-bobcats-pay.md
- packages/gatsby-theme-learning/src/components/course-complete-modal.tsx
You've now completed this **course** and unlocked a new skill! -> You've now completed this **module** and unlocked a new skill!
> chore: changing modal text

- .changeset/large-tigers-hope.md
- packages/gatsby-theme-sso-ui-kit/src/components/avatar.js
> [SL] Don't show login buttons in loading state

- .changeset/serious-clouds-relate.md
- packages/ui-kit/src/components/code-block.tsx
- websites/docs-smoke-test/src/content/views/markdown.mdx
> Support empty code blocks without build errors

- .changeset/khaki-items-battle.md
- packages/gatsby-theme-api-docs/src/components/resource/method/highlights.js
- packages/gatsby-theme-api-docs/src/components/type/properties/rows/description.js
- packages/ui-kit/src/components/markdown.tsx
- packages/ui-kit/src/design-system.ts
> [Design adjustments] Change colors to follow the WCAG

- .changeset/early-pugs-sit.md
- cypress/e2e/self-learning-smoke-test/02-profile-modal.feature
- packages/gatsby-theme-docs/src/components/config-context.ts
- packages/gatsby-theme-docs/src/modules/self-learning/README.md
- packages/gatsby-theme-docs/src/modules/self-learning/components/user-profile-init.tsx
- packages/gatsby-theme-docs/src/modules/sso/components/avatar.js
- packages/gatsby-theme-docs/src/modules/sso/hooks/use-authentication.ts
- packages/gatsby-theme-docs/src/modules/sso/hooks/use-local-storage-session.ts
- websites/self-learning-smoke-test/gatsby-config.mjs
closes  commercetools/learning-tech#450
> feat: cross tab session sync

- .changeset/small-comics-whisper.md
- packages/ui-kit/src/components/markdown.tsx
just a small adjustment of the ClipboardIcon position.
> [Design adjustments] Align ClipboardIcon with section header text

- .changeset/odd-ads-roll.md
- packages/ui-kit/src/components/markdown.tsx
These changes were all discussed with the @commercetools/tech-writers team and @zbalek.
For more information:
https://commercetools.slack.com/archives/GCJ66P3PS/p1690382944822279
> [Design adjustments] Last design changes for the upcoming release

- .changeset/witty-glasses-share.md
- api-specs/test/api.raml
- packages/gatsby-theme-api-docs/src/components/resource/method/method.js
- packages/gatsby-theme-api-docs/src/components/resource/method/request-response-examples.js
- packages/gatsby-theme-api-docs/src/components/resource/method/responses.js
- packages/gatsby-theme-api-docs/src/hooks/use-api-resources.js
- packages/gatsby-theme-api-docs/src/utils/render-type-as-link.js
- packages/gatsby-transformer-raml/src/utils/resource/process-methods.mjs
> Display content types for responses correctly

- .changeset/itchy-ducks-act.md
- packages/gatsby-theme-docs/src/modules/self-learning/components/course-complete-modal.tsx
support team just did a change that affects us and it requires this link change
> fix: adjust support link

- .changeset/polite-apricots-move.md
- packages/ui-kit/src/components/mermaid-client-side.tsx
- websites/docs-smoke-test/src/content/components/mermaid-diagram.mdx
- websites/documentation/src/content/writing/images.mdx
> ``[Mermaid diagrams]`` Enable configurable automatic numbering

- .changeset/soft-rules-compare.md
- packages/gatsby-theme-docs/src/components/plan-tag-internal.js
- packages/ui-kit/src/components/markdown.tsx
- websites/docs-smoke-test/src/content/views/beta.mdx
> Fix beta tag spacing in lists with link entries

- .changeset/lovely-planes-arrive.md
- packages/gatsby-theme-docs/src/modules/self-learning/components/profile-modal.tsx
closes https://github.com/commercetools/commercetools-docs/issues/4226
> [Self-learning] Fix text overflow in account association dialog

- .changeset/pink-adults-occur.md
- packages/writing-style/styles/commercetools/PortfolioNaming.yml
Remove internal link in the `PortfolioNaming` message.
> Remove link from PortfolioNaming

- .changeset/eighty-eels-flash.md
- packages/gatsby-theme-docs/src/layouts/internals/layout-release-note-body.js
closes https://github.com/commercetools/commercetools-docs/issues/4387
> Change color of the release note label "Resolved Issue"

- .changeset/late-impalas-double.md
- packages/writing-style/styles/commercetools/Acronyms.yml
closes https://github.com/commercetools/commercetools-docs/issues/4825
> [Writing styles] Adjust acronym check to accept compound nouns spelled out with lowercased initials

- .changeset/empty-panthers-help.md
- packages/gatsby-theme-docs/src/layouts/internals/footer.js
closes https://github.com/commercetools/commercetools-docs/issues/4427
> Make footer banner clickable

- .changeset/hip-boats-impress.md
- packages/gatsby-theme-docs/src/modules/ai-assistant/components/chat-modal.jsx
- packages/gatsby-theme-docs/src/modules/ai-assistant/components/chat.utils.js
@FFawzy I'll add a task to create a E2E scenario covering this case.
> fix: prevent unverified emails to access ai chat

- .changeset/tasty-keys-attend.md
- packages/gatsby-theme-docs/src/overrides/topbar-login-info.js
changing the default mode for ai assistant to Gemini
> feat: changing the default mode for ai assistant to Gemini

- .changeset/olive-suns-battle.md
- packages/gatsby-theme-docs/src/hooks/use-release-notes-config.js
> chore: fix the product and productArea value inversion

- .changeset/wet-wasps-repeat.md
- packages/ui-kit/src/components/rss/rss-feeds.spec.ts
- packages/ui-kit/src/components/rss/rss-feeds.tsx
part of https://github.com/commercetools/learning-tech/pull/656
> fix: adjust rss custom tag name

- .changeset/mighty-humans-pump.md
- api-specs/test/api.raml
- packages/gatsby-theme-api-docs/src/components/info-value.js
- packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
- packages/gatsby-theme-api-docs/src/components/resource/method/query-parameters.js
- packages/gatsby-theme-api-docs/src/components/type/properties/rows/description.js
- packages/gatsby-theme-api-docs/src/hooks/use-api-resources.js
- packages/gatsby-transformer-raml/src/schema/define-raml-resource.mjs
- packages/gatsby-transformer-raml/src/utils/parameters-to-array.mjs
> Support default values for query parameters

- .eslintrc.js
**Description of changes**
- Technical improvement adding a linting rule to disable imports from specific packages accessing src
> feat: add lint rule disable src import
