commercetools/commercetools-docs-kit

- packages/gatsby-theme-docs/index.js
Those exports are currently what is needed for the appkit website, to avoid having the imports reaching into the internal folders.
Eventually we can move some of those things into a separate package that contains ui components.
> feat(theme): export some of the things needed in the appkit website

- packages/gatsby-theme-docs/gatsby-config.js
- packages/gatsby-theme-docs/src/components/markdown.js
- packages/gatsby-theme-docs/src/layouts/internals/globals.js
- packages/gatsby-theme-docs/src/templates/page-content.js
- websites/docs-smoke-test/src/content/images/image-with-caption.mdx
- websites/docs-smoke-test/src/content/images/image.mdx
- websites/docs-smoke-test/src/content/images/inline-image.mdx
- websites/docs-smoke-test/src/content/images/svg-image.mdx
- websites/docs-smoke-test/src/content/images/tall-image.mdx
- websites/docs-smoke-test/src/content/images/transparent-image.mdx
> fix(theme): use built-in image caption

- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
Leftover of #29 
TL;DR: the generated page slug should also not have a trailing slash. I noticed this as Gatsby was throwing some warnings of hot reloads.
```
warn Attempting to create page "/views/empty/", but page "/views/empty" already exists. This could lead to non-deterministic routing behavior
```
> fix: remove page slug trailing slash

- .gitignore
- .vscode/settings.json
So our [PR](https://github.com/testthedocs/vscode-vale/pull/8) for make the extension configurable got merged and released yesterday. I tried this out now and it works!
However, the `mdx` files are [being ignored by the extension](https://github.com/testthedocs/vscode-vale/blob/de4ab0bab73774f01d1ee3114bc84a806db0c3c5/src/extension.ts#L275). I'll open a new PR to add the `mdx` extension and maybe to also make it configurable.
> chore: use vale local bin for vscode

- packages/gatsby-theme-docs/src/components/subtitle.js
Since `<Subtitle>` can contain/render markdown syntax, the wrapper element should be a `div`.
This avoids warnings where `<p>` only accepts a subset of child element types.
> fix(theme): use div element for subtitle

- packages/gatsby-theme-docs/gatsby-config.js
- packages/gatsby-theme-docs/index.js
- packages/gatsby-theme-docs/src/components/index.js
- packages/gatsby-theme-docs/src/components/theme-provider.js
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/overrides/README.md
- packages/gatsby-theme-docs/src/overrides/use-additional-site-data.js
- packages/gatsby-theme-docs/src/templates/page-content.js
- websites/docs-smoke-test/gatsby-config.js
This PR adds a new extension point regarding custom site metadata that websites might use (e.g. appkit).
It also exposes a new component `ThemeProvider` that should be rendered by any page template so that the data is available in React context.
> feat(theme): expose theme provider for extending site metadata

- .vscode/settings.json
Based on this: https://github.com/testthedocs/vscode-vale/pull/12
> chore: use new setting syntax for vscode vale extension

- packages/gatsby-transformer-raml-legacy/README.md
- packages/gatsby-transformer-raml-legacy/package.json
I messed up npm scope vs. repo name again, sorry.  Found out only after merging because the publish CI failed
> fix: npm scope that actually exists

- packages/gatsby-theme-docs/gatsby-config.js
- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-theme-docs/src/components/seo.js
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/templates/page-content.js
- websites/docs-smoke-test/gatsby-config.js
- websites/site-template/gatsby-config.js
Closes #88 
By default the option `excludeFromSearchIndex` is `false`, which means websites can be crawled. You need to explicitly opt-in to disable the crawling on the entire site or on a page level (only via the navigation.yaml)
> feat(theme): allow to configure robots noindex

- packages/gatsby-theme-docs/src/layouts/internals/page-navigation.js
> fix(theme): give more padding for page navigation scrollbar

- packages/gatsby-theme-docs/create-emotion-cache.js
- packages/gatsby-theme-docs/gatsby-browser.js
- packages/gatsby-theme-docs/gatsby-ssr.js
- packages/gatsby-theme-docs/package.json
- yarn.lock
Fixes #121 
SSR (Server Side Rendering) works out-of-the-box in Emotion, however the [default approach](https://emotion.sh/docs/ssr#default-approach) is to insert a `<style>` tag above each element with styles.
This has a problem though, as pointed out in the Emotion docs:
> Warning: This approach can interfere with nth child and similar selectors as it is inserts style tags directly into your markup. You will get a warning if you use such selectors when using this approach.
This is exactly the root of the issue we're seeing, as we make use of the [lobotomized owl selector](https://alistapart.com/article/axiomatic-css-and-lobotomized-owls/).
To fix this problem, Emotion [suggests to implement SSR on our own](https://emotion.sh/docs/ssr#advanced-approach), following certain guidelines, …
> fix(theme): SSR style tags messing with nth selectors

- packages/broken-link-checker/broken-link-checker.js
- packages/broken-link-checker/package.json
- yarn.lock
We need this option for the migration phase, as some links are detected as broken.
For example, a link to https://docs.commercetools.com/http-api-authorization is detected as broken, as we assume that this is an "internal" link and therefore remove the domain origin. However, because of the "legacy" URL structures, this is a valid link that will only work on the live domain.
https://github.com/stevenvachon/broken-link-checker#excludedkeywords
> refactor(broken-link-checker): allow to pass excluded-keywords option

- packages/gatsby-theme-docs/index.js
- packages/gatsby-theme-docs/src/components/code-block.js
- packages/gatsby-theme-docs/src/components/index.js
- packages/gatsby-theme-docs/src/components/markdown.js
TL;DR: allows to use the `<CodeBlock>` component "outside" of the MDX context.
The base `<CodeBlock>` component now accepts specific props (`language`, `content`, etc.) which allows it to be used as a normal component. For the mdx component mapping, we provide a wrapper component that maps the mdx props.
> refactor(theme): to expose CodeBlock component with generic props (no mdx specific)

- packages/gatsby-theme-docs/src/components/markdown.js
To give a bit more breathing space to the list items.
Example:
> fix(theme): list items spacing

- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
- websites/api-docs-smoke-test/gatsby-config.js
- websites/docs-smoke-test/gatsby-config.js
- websites/site-template/gatsby-config.js
> refactor(theme): do not render search bar when excludeFromSearchIndex is true

- package.json
This PR adds a script to check if the user is logged into npm **before** starting the release process. This prevents "dirty releases", where lerna bumps versions and pushes a new tag, only to fail after that when trying publish packages to npm as the user is not logged in.
> chore: check npm login before building a release

- websites/api-docs-smoke-test/src/api-specs/test/api.raml
Corrected the descriptions of the expected order, as "Should display 3rd" was missing.
I also included `OutOfOrderPropertiesTestType.properties.version`.
> fix: corrected expected order of properties

- packages/gatsby-theme-api-docs/src/components/api/resource/method/request-representation.js
- packages/gatsby-theme-api-docs/src/components/api/resource/resource.js
Based on the design [here](https://commercetools.invisionapp.com/d/main?origin=v7#/console/17784193/388243826/preview?scrollOffset=1152).
Will close https://github.com/commercetools/commercetools-docs-kit/issues/200
> Resource design implementation

- packages/ui-kit/src/components/code-block.js
- packages/ui-kit/src/components/globals.js
- packages/ui-kit/src/components/markdown.js
As requested by @Shecki , this is an attempt to improve the visual grouping of some elements, by adjusting the spacing between then.
> refactor(theme): adjust spacings of some elements to improve visual grouping

- packages/gatsby-theme-docs/src/components/beta-flag.js
Small fix to ensure that the link does not get an underline (apparently the behavior is somehow different between chrome and firefox)
> fix(theme): beta style link

- packages/gatsby-theme-docs/src/components/search-input.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
- packages/ui-kit/src/design-system.js
When the website has `excludeFromSearchIndex` set to true, the search input should not be visible and be triggered in any way.
This PR enforces the input to be "disabled", as well as to disable the keyboard event handlers to activate the search.
> fix(theme): disable search input when website has search index disabled

- packages/writing-style/vale-styles/commercetools/Brand.yml
As suggested by @adinakleine 
> Custom Application is an established ct term due to this it has to be capitalized.
> fix(writing-style): make custom apps capitalized

- jest.prettier.config.js
- lint-staged.config.js
- package.json
- recommended.code-workspace
The prettier parser for markdown does not work well with mdx. The prettier mdx parser also does not work well.
I’ll disable auto formatting of mdx files for now until we find a good solution.
Some related issue that I found: https://github.com/luckylwk/hoppin-design-system/pull/21
For example: with this mdx content:
```
1. hey
<Info>
This is indented
</Info>
```
When prettier runs with parser: markdown  it gets like this
```
1. hey
<Info>
This is indented
</Info>
```
Notice the indentation is lost.
For now we keep it disabled.
> chore: do not format mdx files with prettier

- packages/gatsby-theme-docs/src/components/beta-flag.js
- packages/gatsby-theme-docs/src/components/global-navigation-link.js
- packages/gatsby-theme-docs/src/components/link.js
- packages/ui-kit/src/components/link.js
This helps to avoid having to override styles directly, but instead changing the appearance via a prop.
> refactor(theme): to make the link underline style configurable via a prop

- packages/gatsby-theme-docs/src/components/link.js
- packages/gatsby-theme-docs/src/components/link.spec.js
- packages/ui-kit/src/components/markdown.js
Fixes #255 
The `role` attribute is not meant to be used like this. I couldn't find any other ARIA attribute to describe the type of a link, so I opted to use a `data-link-type` attribute.
> fix(theme): use data-link-type instead of aria role attribute

- packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
This reverts commit ab8f1c84aadc8cbd6e15034e35f601c3ca3ac020.
Let's see if the VRTs now are "correct" (https://github.com/commercetools/commercetools-docs-kit/pull/260#issuecomment-580653513)
> Revert "chore(theme): temporary change sidebar bkg color, to reset VRTs"

- packages/gatsby-theme-api-docs/gatsby-config.js
- packages/gatsby-transformer-raml/README.md
- packages/gatsby-transformer-raml/gatsby-node.js
- packages/gatsby-transformer-raml/src/create-api-node.js
- packages/gatsby-transformer-raml/src/create-resource-node.js
- packages/gatsby-transformer-raml/src/create-type-node.js
- websites/api-docs-smoke-test/gatsby-config.js
Closes https://github.com/commercetools/commercetools-docs-kit/issues/230
> refactor: expose gatsby-transformer-raml options

- package.json
TL;DR: canary releases only publish packages that changed in the last commit. This sometimes results in "broken" packages that refer to wrong versions, as multiple canary releases might not include the same package version.
See https://github.com/lerna/lerna/issues/2060
To ensure that each canary release is fully functioning, we can force all packages to be published.
> fix: force canary releases to always publish all packages

- cypress/integration/docs-smoke-test/menu-navigation.js
- cypress/integration/docs-smoke-test/top-menu.js
- cypress/integration/docs-smoke-test/viewports.js
- packages/gatsby-theme-docs/src/components/content-pagination.js
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-header-side.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
- packages/gatsby-theme-docs/src/layouts/internals/page-content-inset.js
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
This
* marks more navigation elements as `<nav>` to exclude them from the body content flow
* marks the top right corner area (e.g. Github link and version) as `<aside>` to exclude it from the content flow (when reading the DOM linearly it's positioned between the Title H1 and the content)
* marks the page content as `<article>` to address it semantically without having to adress the complete `<main>` which includes more.  It would have been nicer to put the <main> nearer to the body content but the grid-oriented DOM does not allow that (main should not contain things that are the same across many sites like in our case the top nav)
* gives the actual markdown generated body content a `body-content` ID in the DOM (for transparency, not directly needed yet)
* introduces a `site-title` ID …
> refactor: use more semantic HTML elements for the search crawler

- scripts/release_canary.sh
In #276  we forced all packages to be published.
However, when commits do not contain any changes in packages, lerna tries to publish `null` versions.
This seems to be a known issue in lerna (https://github.com/lerna/lerna/issues/1769).
This PR attempts to fix that, by triggering the release only if lerna detects that packages have changed. For that, we can use the `lerna changed` command.
> fix: publish canary only if lerna detects that packages changed

- packages/gatsby-theme-docs/src/components/overlay.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
Problem: the search container results does not scroll with the page.
In the production bundle, the css override styles didn't get properly applied, so that the default styles of the overlay were still used. This could be solved by using `!important`, but it's not the best solution.
In this PR we pass the override styles as props, so that the final bundle contains the correct applied styles.
> fix(theme): css overrides for search overlay

- packages/ramldoc-generator/.gitignore
- packages/ramldoc-generator/README.md
- packages/ramldoc-generator/package.json
- packages/ramldoc-generator/scripts/download-rmf-codegen.js
- packages/ramldoc-generator/src/cli.js
- packages/ramldoc-generator/src/main.js
- yarn.lock
This automatically downloads the rmf-codegen JAR at install time like we do for the vale language linter. 
Plus an overhaul of some of the README sections, explaining more why and what this does. 
Some of the open comments in #296  will be obsolete but not all (not the CLI related polish that is open)
The jar now has the version in the file name to increase transparency and to make sure it's reliably downloading the newest version when the package is upgraded.
> path into raml-generator PR:  automatically download rmf-codegen, polish

- .eslintignore
- packages/gatsby-theme-docs/README.md
- packages/gatsby-theme-docs/gatsby-config.js
- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-theme-docs/package.json
- packages/gatsby-theme-docs/src/components/code-example.js
- packages/gatsby-theme-docs/src/components/index.js
- packages/gatsby-theme-docs/src/hooks/use-code-examples.js
- packages/gatsby-theme-docs/src/templates/page-content.js
- packages/gatsby-transformer-code-examples/LICENSE
- packages/gatsby-transformer-code-examples/README.md
- packages/gatsby-transformer-code-examples/gatsby-node.js
- packages/gatsby-transformer-code-examples/index.js
- packages/gatsby-transformer-code-examples/package.json
- packages/ui-kit/src/components/code-block.js
- packages/writing-style/vale-styles/commercetools/Acronyms.yml
- websites/docs-smoke-test/src/code-examples/example.cs
- websites/docs-smoke-test/src/code-examples/example.curl
- websites/docs-smoke-test/src/code-examples/example.graphql
- websites/docs-smoke-test/src/code-examples/example.java
- websites/docs-smoke-test/src/code-examples/example.js
- websites/docs-smoke-test/src/code-examples/example.json
- websites/docs-smoke-test/src/code-examples/example.php
- websites/docs-smoke-test/src/code-examples/example.sh
- websites/docs-smoke-test/src/code-examples/example.ts
- websites/docs-smoke-test/src/code-examples/example.yml
- websites/docs-smoke-test/src/content/components/code-examples.mdx
- websites/docs-smoke-test/src/data/navigation.yaml
- yarn.lock
We chose to implement and provide a practically working approach that uses the same architecture as the RAML type rendering to be able to move on with the migration of the site independenly of whether we get the babel / webpack loader <-> MDX  related issues sorted out. 
`@commercetools-docs/gatsby-transformer-code-examples` transforms file contents into CodeExample types in available in graphql. Supported file formats are:
- cs
- graphql
- java
- js
- json
- php
- sh
- ts
- yaml
`CodeExample` component uses the hook query `use-code-examples.js` to query CodeExample types and then return content wrapped with `CodeBlock` component.
Technically, any file in the project, with supported format can be rendered as an example but it is recommended to stick the the `code-examples` directory for …
> feat: code examples provided on graphQL by a transformer plugin 

- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-theme-docs/package.json
- websites/docs-smoke-test/gatsby-config.js
- websites/docs-smoke-test/src/releases/release-format-definition.mdx
- yarn.lock
Changes here include:
* date
* description
* type
* topics
* Release notes overview page - `/releases`
* Release note details pages - `/releases/<date>-<title>`
> feat(release-notes): Release notes fields and paths

- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-theme-docs/src/hooks/use-layout-state.js
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
> fix: leftovers of release notes layout implementation

- packages/gatsby-theme-docs/gatsby-browser.js
- packages/gatsby-theme-docs/gatsby-ssr.js
addresses #346 
This is the technique that is used on the current docs.commercetools.com  site - it's a client side approach that activates a CSS rule that removes the complete thing from the visible DOM, letting it do it's buggy work however it wants as long as it doesn't show up. 
The check is on the .commercetools.com  domain level because that's the cookie scope the script uses. 
The root cause it that the cookie consent script fails on other domains and does not close.
> fix(theme): dynamically render the cookie consent scripts only on *.commercetools.com domain

- packages/writing-style/README.md
- packages/writing-style/package.json
- packages/writing-style/vale-styles/commercetools/Acronyms.yml
- recommended.code-workspace
* provides a local "raw"  vale command that the config can be directly passed to.  This proved more robust when using the VSCode plugin. 
* adjust recommended VSCode workspace to use the config directly from the package to make transparent that it's not the same as an NPM version.  Also allows for quicker local feedback in the editor when tuning the rules. 
* add a few acronyms that are common in software development 
* allow the "ZEIT" brand in acronymys (false negative, it's not an aconym).
> Tune writing style checker for plugin compatibility and custom apps

- .stylelintrc
- cypress/integration/docs-smoke-test/top-menu.js
- package.json
- packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
Fixes #345 
It works for Chrome and Safari. On Firefox I wasn't able to make it work, but it seems that Firefox has problems with printing pages in general.
> fix(theme): to use height auto for small screens

- packages/gatsby-theme-docs/src/data/top-side-menu.yaml
The integrations marketplace is going live (earliest) 6th of april and should then be linked from the meta navigation part of the docs site. 
Do not merge or release this before 6th of April and confirm back with  @nkuehn  before going live.
> Nav Content: Add Integrations marketplace to meta nav

- packages/gatsby-theme-docs/gatsby-config.js
- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-transformer-code-examples/gatsby-config.js
- packages/gatsby-transformer-code-examples/gatsby-node.js
The appkit ui components pages are currently broken because their are not built anymore.
This was because we assumed that the pages were built only from the `sourceInstanceName: content` (my mistake).
Additionally, I moved the sourcefile for the code examples into its related transformer, to keep things tight together.
> fix(theme): to not restrict content page nodes for specific filesystem

- packages/gatsby-theme-docs/src/components/beta-flag.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-header.js
- packages/gatsby-theme-docs/src/markdown-components.js
- packages/ui-kit/src/design-system.js
- websites/docs-smoke-test/src/content/index.mdx
To make the beta flag usable in any content its size is changed
to a relative measure calculated from the design spec.
To align it visually straighter it's middle-aligned with the surrounding text now.
The change leads to factual beta badge size changes in the area of < 1px  because I wanted to keep re-using the design system values instead of calculating theoretical font sizes e.g. for the page header.  
It's good for me this way and overall the better solution than to have to maintain a badge style for every potential situation it's used in
> feat(docs-theme): make beta flag available in any content

- .percy.yml
- cypress/integration/docs-smoke-test/viewports.js
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-main.js
- packages/gatsby-theme-docs/src/layouts/release-notes-detail.js
- packages/gatsby-theme-docs/src/layouts/release-notes-list.js
- packages/ui-kit/src/components/globals.js
In #347 we attempted to fix the container `height` in order for the page to be printable.
However, the media query (including the `percy` agent) didn't really work, resulting in the `height: 100vh` to never be applied and thus the page nav on the right to not be sticky.
This PR removes the `percy` agent media query and uses instead a normal CSS selector in order for Percy to take full page snapshots.
It also fixes the page content to not scroll when the sidebar menu and top menu are open (with the overlay).
I also added a Cypress test with the intent of preventing regressions for the sticky behavior.
> fix(theme): sticky page nav and scrolling container

- packages/gatsby-theme-docs/gatsby-config.js
- websites/docs-smoke-test/src/content/index.mdx
Since all of our processing and especially prettier is following the commonmark spec the site needs to understand backslashes as newlines.
This requires passing the commonmark option to MDX which is passed down to all remark plugins by mdx.
> fix(theme-docs): Render mdx commonmark compliant

- packages/gatsby-theme-docs/src/layouts/internals/page-navigation.js
- packages/gatsby-theme-docs/src/layouts/internals/page-navigation.spec.js
Fixes #389 
TL;DR: if nested headings are missing a "level" in between, the TOC would throw an error.
For example, if heading 2 `##` is missing:
```
Content
Content
```
Now if a heading is missing, in dev mode we log a warning and show a notification error in the TOC:
> fix(theme): gracefully handle missing heading level in TOC

- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-theme-docs/package.json
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/utils/process-table-of-content-fields.js
- packages/gatsby-theme-docs/src/utils/process-table-of-content-fields.spec.js
- yarn.lock
Fixes #392 
Since we use [rehype-slug](https://github.com/rehypejs/rehype-slug) to generate header IDs which are in turn used for header anchors, this change regenerates `tableOfContent` url using [github-slugger](https://github.com/Flet/github-slugger) which [github-slugger](https://github.com/Flet/github-slugger) uses to generate slugs. The change also includes stripping out JSX from titles of tableOfContent.
> fix: inconsistent url and title or index nav

- recommended.code-workspace
Just "recommended" is not helpful as a window title if you have multiple vscode windows open. 
This sets the default VSCode convention and adds the repo name to it
> enhancement(workspace): set the window title better find the window

- packages/writing-style/.vale.ini
- packages/writing-style/styles/commercetools/Acronyms.yml
- packages/writing-style/styles/commercetools/DateFormat.yml
- packages/writing-style/styles/commercetools/FirstPerson.yml
- packages/writing-style/styles/commercetools/Weasel.yml
- packages/writing-style/styles/commercetools/WordList.yml
Vale writing style check shows some minor issus. 
Due to this some rules have to be adjusted:
- acronym (add exceptions: ENUM, PSR, SDL, VAT, VIP) 
- `Google.Quotes: commas and periods go inside quotation marks.` Rule is not useful for us.
- `commercetools.DateFormat`is not working properly. 
- `commercetools.WordList - single sign-on`is not working properly.
> WIP writing style: adjustments

- packages/gatsby-theme-api-docs/README.md
- packages/gatsby-theme-api-docs/gatsby-config.js
- packages/gatsby-theme-api-docs/package.json
- websites/api-docs-smoke-test/gatsby-config.js
- websites/api-docs-smoke-test/package.json
This is a small but powerful change, that's also a breaking change because sites that use the API docs theme have to be reconfigured to require and configure the API theme and the docs theme separately. 
**Background**
The commercetools-docs repository now contains six websites, of whome one (and later two) are using the API docs theme because they generate docs from RAML. 
The commercetools-docs repository also has a central "wrapper" theme that provides central configuration (e.g. the theme version, the google analytics key, etc) and data (navigation links in preview branches, **limits data**). 
**Problem**
The (in that repo) central configuration and data still has to be maintained twice for the sites using the API theme and the plain docs theme to avoid the base theme being loaded and …
> refactor(api-theme): compose themes in website instead of inheriting

- websites/docs-smoke-test/src/content/components/cards.mdx
- websites/docs-smoke-test/src/data/navigation.yaml
This is Step one to resolve / #414 / 
It's in a first brainstorming phase, don't take it as a fixed definition - it's useful to force us taking some technical design decisions (like allowing markdown in the content or not) and then approve this as the test case page for the implementation.
> docs(cards): draft authoring spec proposal for cards

- .changeset/config.json
We should be fine like this for now, let's keep it simple.
> chore(changesets): keep it simple, no linked packages

- .changeset/warm-kids-sparkle.md
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-release-notes-filters.js
> fix(theme): render release notes filters in overlay for small screens

- .changeset/refactor-content-spacing.md
- packages/ui-kit/src/components/content-notifications.js
- packages/ui-kit/src/components/markdown.js
- packages/ui-kit/src/components/multi-code-block.js
- packages/ui-kit/src/components/subtitle.js
- refactor-content-spacing.md
- websites/docs-smoke-test/src/content/components/content-notifications.mdx
Resolves #451 
---
As a counterpart to the `TypographyPage` wrapper, the Markdown UI components now export a `TypographyContainer` wrapper which is supposed to be used in use cases like Cards, Notifications, Subtitle, Table Cells etc. - overall, in places where markdown content is rendered not in the main body flow but inside a visual enclosure. 
In such enclosures the standard spacing is too large and some of it (like bottom margins) should never applied at all.  
Spacing that is specific to the main page content typography is pulled out of the specific components into the wrappers.  
The TypographyPage wrapper is to be applied to Card content, too once merged
---
In addition, this makes a small adjustment to the spacing of nested lists and lists:  Lists previously had very different …
> feat(markdown): refactor content spacing to better render enclosed fragments

- .changeset/good-dryers-worry.md
- packages/gatsby-theme-docs/src/components/card.js
- websites/docs-smoke-test/src/content/components/cards.mdx
This is a follow up to https://github.com/commercetools/commercetools-docs-kit/pull/454
> refactor: render non string card body in typography container

- .changeset/spicy-hotels-buy.md
- packages/gatsby-theme-docs/gatsby-config.js
Closes https://github.com/commercetools/commercetools-docs-kit/issues/449
> fix: removes rss related warning of missing title when building

- .changeset/twenty-impalas-tease.md
- packages/gatsby-theme-docs/src/components/child-sections-nav.js
- packages/ui-kit/src/components/markdown.js
- websites/docs-smoke-test/src/content/views/two-level-index-nav.mdx
This addresses two issues
* fixes a regression that gave lists too small top spacing (introduced when refactoring the spacing)
* fixes problems with very long words in headings flowing into the next column in the child section navigator component
* gives the child section navigator component more column gap to improve readability in nested scenarios.
> Fix spacing and word wrap in child navigation and lists

- .changeset/bright-gorillas-chew.md
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
Otherwise we get an empty string as the link.
> fix(theme): back to docs link from release notes pages

- websites/docs-smoke-test/src/content/views/markdown.mdx
- websites/docs-smoke-test/src/topics/complex-blockquote.mdx
- websites/docs-smoke-test/src/topics/list-items.mdx
This addresses #473 
It's working fine here but I'm still worried why I experience unformatted transcluded documents in the content repository when using a canary kit build.
> Use mdx transclusion in a tested page

- .changeset/empty-walls-whisper.md
- packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
> fix(theme): push footer to bottom, even when content is very short

- .changeset/violet-numbers-begin.md
- packages/gatsby-theme-docs/src/components/cards.js
The removed check fixes issues of UI elements breaking in some cases.
> refactor: allow cards to accept arbitrary children in non mdx files

- .github/workflows/release.yml
Same as in the appkit and uikit repo, we use a personal access token from our `ct-release-bot` account, which allows to trigger multiple github workflows (not possible using the default github token).
For instance, when the "Version packages" PR gets opened/updated, the main workflow should now be triggered.
PS: the secret is already in place.
> chore(actions): use personal access token to allow triggering multiple workflows

- .changeset/sour-shirts-rest.md
- packages/ui-kit/src/components/code-block.js
- packages/ui-kit/src/prism-themes/commercetools.js
- packages/ui-kit/src/prism-themes/commercetoolsLight.js
- websites/docs-smoke-test/src/content/components/code-blocks.mdx
- websites/docs-smoke-test/src/content/views/code-blocks.mdx
- swap the "neon" yellow for a less agressive one provided by design
- swap two colors to improve JSON understandability
- homogenize numbers and bools across light / dark to ease JSON understandability
@sven this is the experimental implementation of the color code you sent me plus improving the test examples plus a try to slightly homogenize the _JSON_  highlighting across light and dark. 
JSON is 80% of the example content that is initially read and seen so optimizing for JSON stands before other languages. 
(I'll send a deeplink to the test once it's built)
> Code Highlighting: tune syntax highlight color scheme

- .changeset/calm-wasps-begin.md
- packages/gatsby-theme-api-docs/package.json
- packages/gatsby-theme-code-examples/package.json
- packages/gatsby-theme-constants/package.json
Might be related to what we observed about a major version being bumped.
Possible related issue: https://github.com/atlassian/changesets/issues/380
> chore: use version range for peer deps

- .changeset/dirty-kids-walk.md
- .changeset/odd-flowers-jump.md
- packages/gatsby-theme-docs/gatsby-config.js
- packages/ui-kit/src/components/rss-feeds.js
- websites/docs-smoke-test/src/content/components/rss-feeds.mdx
fixes #589 
* the starting from filter for RSS feeds was only an artifact from development setups.  It caused issues because GatsbyJS or MDX seems to be unstable concerning date parsing in YAML frontmatter.  Gatsby releases switch back and forth between parsing as date or not. 
* changes the VRT setup to point to a stable feed (the local one of the test site) that does never change. 
* avoids breaking line inside the date to provide stable layouts independent of the text content of the RSS feed (still readable  enough in mobile views.
> Remove unnecessary date filter from RSS feed query

- .changeset/short-adults-wonder.md
- packages/gatsby-theme-docs/gatsby-browser.js
- packages/gatsby-theme-docs/gatsby-config.js
- packages/gatsby-theme-docs/package.json
- yarn.lock
I noticed that the google fonts haven't been loaded properly. After a bit of research, [I found](https://www.gatsbyjs.com/docs/recipes/styling-css/#using-google-fonts) that using something like the typeface packages seems like the preferred approach.
> fix: load fonts using typeface packages

- .changeset/gold-mayflies-marry.md
- jest.text.config.js
- packages/writing-style/.gitignore
- packages/writing-style/package.json
- packages/writing-style/scripts/download-vale.js
- packages/writing-style/src/run.js
- packages/writing-style/vale-bin/.gitignore
- recommended.code-workspace
* adjust the vscode workspace config to new plugin
* updates the vale version to latest (a lot of text parsing robustness has happened in the last months)
vale started to include license and readme into the release archives.
To avoid overwriting our own readme and license, the vale distribution now lives in a subfolder again
> writing-style: upgrade to vale 2.3.4, new vscode plugin

- .changeset/calm-masks-hunt.md
- packages/gatsby-theme-docs/gatsby-node.js
For authors, all release notes images must go into the `src/images/releases` directory. So this change addresses that need.
> auto-generate src/images/releases directory

- .changeset/pretty-suns-love.md
- packages/writing-style/.gitignore
- packages/writing-style/scripts/download-vale.js
Caused by #665 
```
error /xxx/node_modules/@commercetools-docs/writing-style: Command failed.
Exit code: 1
Command: node scripts/download-vale.js
Arguments: 
Directory: /xxx/node_modules/@commercetools-docs/writing-style
Output:
[writing-styles] Verifying vale installation...
[writing-styles] Installing vale 2.3.4 ...
[writing-styles] Error installing vale binary Error: tar: could not chdir to '/xxx/node_modules/@commercetools-docs/writing-style/vale-bin/'
at abortIfError (/xxx/node_modules/@commercetools-docs/writing-style/scripts/download-vale.js:38:11)
at downloadAndExtractArchive (/xxx/node_modules/@commercetools-docs/writing-style/scripts/download-vale.js:58:3)
```
> fix(writing-style): vale binary installation

- .changeset/afraid-readers-notice.md
- packages/gatsby-theme-docs/gatsby-config.js
This is reducing the number of transform by ca. a third in my tests 
(excluding the separate problem we introduced with the images in the react fragment renderers - these make up 50% at the moment because every image is processed twice).
> a little less image resolution to transform at dev time

- .changeset/seven-glasses-admire.md
- cypress/integration/docs-smoke-test/links.js
- cypress/integration/docs-smoke-test/static-pages.js
- packages/gatsby-theme-docs/README.md
- packages/gatsby-theme-docs/gatsby-node.js
- packages/gatsby-theme-docs/src/components/link.js
- packages/gatsby-theme-docs/src/components/link.spec.js
- websites/docs-smoke-test/src/content/views/links.mdx
- websites/docs-smoke-test/static/downloads/hello.json
- websites/docs-smoke-test/static/downloads/hello.txt
- websites/docs-smoke-test/static/html/hello.html
Fixes #680 
> Note that serving static `.html` pages does not work in development mode. See https://github.com/gatsbyjs/gatsby/issues/13072
This PR settle on a convention that links referencing files, according to the following rules, are rendered as "static" HTML links.
- all files within the `/downloads` folder
- any HTML file (file path ending with `.html`)
Those files MUST be located in the `static` folder (https://www.gatsbyjs.com/docs/static-folder/).
> In the API docs, we already have the files located in the `static` folder.
> fix(theme): render links for static files as static HTML links

- .changeset/calm-suns-crash.md
- packages/gatsby-theme-docs/gatsby-node.js
Fixes https://github.com/commercetools/commercetools-docs-kit/issues/704
> fix: stop duplicating release note pages as content pages

- packages/gatsby-theme-api-docs/package.json
- packages/gatsby-theme-code-examples/package.json
- packages/gatsby-theme-constants/package.json
- packages/gatsby-theme-docs/package.json
- packages/gatsby-transformer-mdx-introspection/package.json
- packages/gatsby-transformer-raml-legacy/package.json
- packages/gatsby-transformer-raml/package.json
- packages/ui-kit/package.json
- packages/writing-style/package.json
To keep things consistent, and to point to the directory of the monorepo where the package lives
> chore: add directory in repository field for each package

- .renovaterc.json
To group major updates of some of our CT monorepositories, for example [like here](https://github.com/commercetools/merchant-center-graphql-explorer/pull/59).
https://docs.renovatebot.com/configuration-options/#sourceurlprefixes
> feat(renovate): group all packages from uikit monorepo for major releases

- .changeset/afraid-coins-deliver.md
- packages/gatsby-theme-docs/README.md
Closes https://github.com/commercetools/commercetools-docs-kit/issues/689
> fix: broken links to release notes samples

- .changeset/neat-glasses-argue.md
- packages/gatsby-theme-docs/package.json
- packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-with-hero.js
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
- packages/ui-kit/src/components/markdown.js
- packages/ui-kit/src/design-system.js
- yarn.lock
Fixes #682 
It appeared that under some unknown circumstances the `props.theme` accessed from within a styled component results in an empty object when building the website in production mode. To fix that, we explicitly pass wherever possible the `theme` object after reading it from the context with `useTheme`.
> fix(docs): to explicitly pass emotion theme when possible

- packages/writing-style/styles/commercetools/WordList.yml
In the new documentation website, we have not only sections, subsection and pages, but also chapters. Thus, we (docs-lectors) would like to stop Vale complaining about the usage of this word, chapter.
> Make "chapter" legal.

- .changeset/wet-walls-brake.md
- packages/gatsby-theme-docs/gatsby-browser.js
- packages/gatsby-theme-docs/package.json
- yarn.lock
The typeface package is deprecated
> refactor: use fontsource instead of typeface package

- .renovaterc.json
This PR changes the renovate schedule config to receive dependency updates every second Wednesday.
Config documentation:
https://docs.renovatebot.com/presets-schedule
The library behind it:
https://bunkat.github.io/later/parsers.html#text
> feat: change schedule of renovate to every second Wednesday

- .changeset/stupid-bugs-press.md
- packages/gatsby-theme-docs/src/components/search-dialog.js
- packages/gatsby-theme-docs/src/components/top-menu.js
See https://github.com/thysultan/stylis.js/issues/245
> fix: regression in Firefox about autoprefixer for height: fit-content

- .changeset/six-peaches-hope.md
- packages/gatsby-theme-docs/gatsby-config.js
- websites/docs-smoke-test/src/content/views/markdown.mdx
Closes https://github.com/commercetools/commercetools-docs-kit/issues/770
> fix: include commonmark in gatsby-plugin-mdx options

- .changeset/curvy-hats-float.md
- packages/gatsby-theme-docs/gatsby-node.js
Caused by #758 
I accidentally removed it, but we still need it because a website can still decide to load SVG files.
> fix(theme): restore SVG loader for webpack

- .changeset/tasty-crews-complain.md
- packages/ui-kit/src/components/code-block.js
Fixes #790 (even though it's not reproducible in this repo).
TL;DR: recently we had seen issues related to styled components (emotion) not getting the theme context, even though the theme is correctly defined in the React context. As a workaround we manually read the theme using `useTheme`, and explicitly pass the `theme` as a prop.
This is a leftover of other related changes.
> fix: code block tooltip to read from theme using hook

- .changeset/fast-schools-eat.md
- packages/gatsby-theme-docs/src/components/release-notes-subscribe-links.js
> fix: remove container with border in release-notes-subscribe-link component

- .changeset/config.json
Just to see if changeset gets less confused when bumping package versions, as sometimes we get major bumps where it's not clear what the reason was.
> refactor(changeset): link only gatsby theme packages

- .github/renovate.json
* Moves renovate config into `.github` folder
* Uses `preserveSemverRanges` instead of `pinOnlyDevDependencies`
Just so that we keep things consistent with other repos.
> chore(renovate): preserve semver ranges

- .changeset/twelve-shirts-help.md
- packages/gatsby-theme-docs/src/components/card.js
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
- websites/api-docs-smoke-test/gatsby-config.js
- websites/docs-smoke-test/gatsby-config.js
- websites/site-template/gatsby-config.js
This PR proposes to enable the following Gatsby feature flags:
- `DEV_SSR: true`
- `FAST_REFRESH: true`
- `PRESERVE_WEBPACK_CACHE: true`
According to Gatsby, this should help improving the performance for local development.
Note that the `DEV_SSR` allows to ensure that a page is correctly rendered on the server (see some of the fixes in the PR as a result of that).
I suggest to checkout the branch and start the websites locally, to make sure that things work fine.
> chore: enable gatsby dev flags to improve development performance

- .changeset/spotty-scissors-nail.md
- packages/gatsby-theme-api-docs/package.json
- packages/gatsby-theme-code-examples/package.json
- packages/gatsby-theme-constants/package.json
- packages/gatsby-theme-docs/package.json
- websites/api-docs-smoke-test/package.json
- websites/docs-smoke-test/package.json
- websites/site-template/package.json
- yarn.lock
We've noticed that the javascript bundle fails on development at the moment. Looks like gatsby has a bug in the new `2.31.1` version. So I downgraded it to `2.30.3` for now.
More information to the bug:
https://github.com/gatsbyjs/gatsby/issues/29213
> fix: javascript bundle fails on development

- .changeset/real-carpets-fry.md
- packages/ui-kit/src/components/markdown.js
closes #797 
@Shecki link to an example: https://commercetools-docs-kit-git-add-outline-to-string-literals.commercetools.vercel.app/docs-smoke-test/views/links
> chore: add outline to string literals

- .changeset/calm-geese-collect.md
- packages/gatsby-theme-docs/index.js
> fix: export <Overlay> and <TopMenu> from core theme

- .changeset/friendly-rivers-develop.md
- packages/gatsby-theme-docs/gatsby-ssr.js
- packages/gatsby-theme-docs/package.json
- yarn.lock
Got this in appkit as I was trying to upgrade.
> fix: add missing raw-loader dependency

- .changeset/chatty-humans-juggle.md
- packages/gatsby-theme-docs/src/components/user-research-banner.js
This PR changes the user research banner text as suggested in the slack channel.
https://commercetools.slack.com/archives/GCJ66P3PS/p1615557841021100
> update user research banner text

- .changeset/silly-actors-remain.md
- packages/gatsby-theme-docs/src/components/child-sections-nav.js
- websites/docs-smoke-test/src/content/components/child-section-navigation.mdx
is part of #899 
This pull request implements code to prevent the entries from overlapping if the line is too long. There is still the discussion in the issue about whether the section names are correct.
This was already discussed and approved from design @Shecki
> Fix overlapping entries in child section nav

- .changeset/itchy-timers-lick.md
- packages/gatsby-theme-docs/bin/create-release-note.js
- packages/gatsby-theme-docs/package.json
- websites/api-docs-smoke-test/package.json
- websites/docs-smoke-test/docs-release-notes-config.yml
- websites/docs-smoke-test/package.json
- websites/docs-smoke-test/release-note-topic-config.yml
closes #862 
If you want to try it out, here's how it works :)
- Open the docs-kit repo in vs code and switch to this branch
- Go to the npm scrips window and open the scripts for either the `docs-smoke-test` or the `api-docs-smoke-test` microsite
- Run the `create-docs-release-note` script. Now you can follow the instructions and create a release note
**Note:**
For showing purposes, I created the config file for the topics only for the `docs-smoke-test`. If you want to see how the script behaves without a config file, run the script in the `api-docs-smoke-test`.
> Improve release note generator

- .changeset/plenty-chicken-yell.md
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
- packages/ui-kit/src/design-system.js
I noticed that there is a two-pixel difference between the placeholder and the searchbox container that you can see during the animation when the search box disappears again. Now the placeholder has the exact same height as the searchbox container.
> refactor: set correct height for searchbox placeholder

- .changeset/brave-impalas-watch.md
- packages/writing-style/styles/commercetools/WordList.yml
Acc. to our beta policy we need to add "closed beta" and "public beta" to the automated writing style checks.
> Terms of beta policy in writing style checks

- .changeset/beige-tables-kick.md
- packages/gatsby-theme-docs/src/components/search-input.js
closes #974 
Unfortunately, the only way to test it is to run it locally
How to test it: open the website in a new tab or do a cash update. Then you can see that you cannot click the search input until the page loads completely.
> disable search input when page is still loading

- README.md
- packages/gatsby-theme-docs/bin/create-release-note.js
- packages/gatsby-theme-docs/package.json
- packages/gatsby-theme-docs/src/components/release-notes-filter-dates.js
- packages/gatsby-theme-docs/src/hooks/use-filtered-release-notes.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
- packages/gatsby-theme-docs/src/plugins/rehype-mdx-section.js
- packages/gatsby-theme-docs/src/templates/release-notes-list.js
- packages/ui-kit/package.json
- packages/ui-kit/src/components/rss-feed-table.js
- packages/ui-kit/src/index.js
- packages/ui-kit/src/utils/code-block-parse-options.js
- packages/ui-kit/src/utils/dates.js
- websites/api-docs-smoke-test/gatsby-config.js
- websites/api-docs-smoke-test/package.json
- websites/docs-smoke-test/package.json
- yarn.lock
Following our discussion concerning the size and performance,  this PR does 
* tweak documentation and start scripts on how to do the bundle size analysis. you can run `yarn build:analyze` as a shortcut to run the bundle analysis on 
* remove the dependency on the full HTML parser "parse5" by doing the metaproperty parsing of code blocks with an own regex based implementation.  (I know, I voted for using the parser, but that was at a time when we needed it for other purposes anyways)
* remove dependency on moment.js  (time library).  It's only gone from our code now but still in some bundle because it's used in the UI Kit calendar widget.   But it's not in all bundles any more now (it was due the RSS feature) but only in the release notes list.
> App Size: Remove dependency to two larger JS libs (moment and parse5)

- .changeset/query-parameter.md
- packages/gatsby-theme-api-docs/.eslintrc.yml
- packages/gatsby-theme-api-docs/src/components/info.js
- packages/gatsby-theme-api-docs/src/components/resource/method/method.js
- packages/gatsby-theme-api-docs/src/components/resource/method/parameters.js
- packages/gatsby-theme-api-docs/src/components/resource/method/query-parameters.js
- packages/gatsby-theme-api-docs/src/components/type/properties/rows/description.js
- packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
- packages/gatsby-theme-api-docs/src/hooks/use-type-to-render.js
- packages/gatsby-theme-api-docs/src/utils/generate-type-to-render.js
- websites/api-docs-smoke-test/package.json
- websites/api-docs-smoke-test/src/content/endpoints/methods.mdx
Closes #1019 
Replaces #1022 
See the query parameters at https://commercetools-docs-kit-git-ao-query-parameter-v2-commercetools.vercel.app/api-docs-smoke-test/endpoints/methods#query-parameters-with-multiple-instances for rendered type and additional description. In this case `sort`, `where` and `/^var[.][a-zA-Z0-9]+$/` has the additional descriptions.
> fix: Misleading Query Parameter Type Rendering

- .changeset/little-gifts-remember.md
- packages/gatsby-theme-docs/src/layouts/content-homepage.js
- packages/gatsby-theme-docs/src/templates/homepage.js
- packages/rmf-codegen/README.md
- packages/rmf-codegen/package.json
This enables using the original RAML baseURI instead of the custom annotation and does not name the examples "postman" any more if they are sourced from the custom `(postman)` annotation
> Upgrade rmf-codegen to version 0.18

- .changeset/modern-guests-speak.md
- packages/gatsby-theme-api-docs/src/hooks/use-type-locations.js
is part of #984 
I have now implemented two indexes for the normal type locations and the type location overrides. After doing some testing, I think this should really improve performance.
> refactor: use indexes for type-locations hook

- .changeset/tiny-pandas-chew.md
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
is part of #1053 
In the docsearch config, we point to the `#site-title` id in order to find the header sections for the result list. Since we implemented the icons next to the site titles, we should move the id only to the actual title and not together with the icon.
> fix: move site-title id to actual site title

- .prettierrc
We want to use the same prettierrc config for raml files as in the docs repo.
See slack discussion [here](https://commercetools.slack.com/archives/GG00MD84Q/p1633334835001200):
> use prettier formatter for raml files

- .github/renovate.json
To reduce the amount of CI, vercel, people and Percy time
we're using due to automated dependency update PRs
this turns of the "lock file maintenance" feature of renovate .
We do not use ranged versions in our packages and also run
automated updates on all dependencies regularly (which implicitly
updates the transitive dependencies, too).  The separate step
of updating transitive dependencies does not provide sufficient value
in this context.  Maybe a few days or one week earlier for some indirect
dependency, but not worth the effort.
> CI: disable renovate lock file maintanance

- api-specs/test/package.json
- package.json
- yarn.lock
This will fix the error we have in the renovate/all branch.
Why renovate doesn't update it on his own is not clear to me. Let's see if this will happen again in the future.
I removed the `percy-cli` downgrade since it works again in the renovate/all branch.
> Update rmf-codegen in api-specs/test

- .github/workflows/main.yml
- .gitignore
- .vercelignore
- package.json
- vercel.json
> Status:   It works in general (on a separate vercel setup to test) but we need an transition phase where vercell still runs the dependency installation.  Issues: 
> * yarn dependency caching seems to not yet be very effective.  install step still takes 2-3 minutes. 
---
This PR migrates the production build step to GitHub actions. It's driven by Vercel's changes in in fee structure which are not favorable any more to use it as a build system.  After all it's consequential, vercel is optimized for the runtime and delivery part and the plan accounts for heavy use of functions, traffic etc..  
Advantages:
-  Simpler billing and capacity structure. Actions are paid by runtime minutes without further constraints like maximum parellelity.  And the runtime minutes have no upper boundary …
> Migrate Builds to GitHub Actions

- .changeset/rude-crabs-fetch.md
- packages/gatsby-theme-api-docs/README.md
- packages/gatsby-theme-api-docs/package.json
- packages/gatsby-theme-code-examples/README.md
- packages/gatsby-theme-code-examples/package.json
- packages/gatsby-theme-constants/README.md
- packages/gatsby-theme-constants/package.json
- packages/gatsby-theme-docs/README.md
- packages/gatsby-theme-docs/package.json
- packages/gatsby-transformer-mdx-introspection/README.md
- packages/gatsby-transformer-mdx-introspection/package.json
- packages/gatsby-transformer-raml/README.md
- packages/gatsby-transformer-raml/package.json
- packages/ui-kit/README.md
- packages/ui-kit/package.json
- packages/writing-style/README.md
- packages/writing-style/package.json
Caused by #1122
PS: The readmes contain links to the new documentation pages. It's important to have the actual file so that in the NPM website you can at least see something and click on the link.
> fix: missing readmes

- .changeset/wild-files-drop.md
- packages/gatsby-theme-docs/src/components/global-notification.js
- packages/gatsby-theme-docs/src/layouts/content-homepage.js
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-global-notification.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-release-notes-filters.js
- packages/ui-kit/src/design-system.js
Follow up of #1202 
Solution for the scroll anchor position has been taken from here: https://getpublii.com/blog/one-line-css-solution-to-prevent-anchor-links-from-scrolling-behind-a-sticky-header.html
> fix: global notification overlap with scroll top anchor positions

- .changeset/tall-mugs-marry.md
- packages/gatsby-theme-docs/src/components/global-notification.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-navigation.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-page-release-notes-filters.js
Follow up of #1209
Hopefully this is the last change.
> fix: keep flexible height for global notification on small viewports

- .github/workflows/main.yml
VRTs must always run on `main`, to have the correct base version against PRs.
> fix(ci): always run tests for VRTs

- .changeset/shy-wombats-wink.md
- packages/writing-style/styles/commercetools/Acronyms.yml
Adds
- TSV
- CHF
- JPY
- GBP
to list of allowed commercetools acronyms.
> Update writing style checker

- .changeset/clean-ants-repair.md
- packages/gatsby-theme-api-docs/package.json
- packages/gatsby-theme-constants/package.json
- websites/documentation/src/content/configuration/packages.mdx
- yarn.lock
Addresses issues with user repositories running on Yarn PnP
> fix: make dependent gatsby plugins actual dependencies

- package.json
- websites/api-docs-smoke-test/src/content/index.mdx
- websites/docs-smoke-test/src/content/index.mdx
- websites/documentation/src/content/index.mdx
- websites/site-template/src/content/index.mdx
At the moment the docs-smoke-test has cards on the index page that contain links to the other microsites which is useful for the deployed website since you can quickly navigate to the smoke test or documentation you need. I suggest to add these cards to all microsites (especially to the new documentation website) so that you can use the link in the index page to get to the smoke test instead of changing the URL.
> [Improvement idea] Add navigation to other microsites

- .changeset/happy-dogs-peel.md
- .github/workflows/main.yml
- packages/gatsby-theme-docs/src/components/card.js
- packages/gatsby-theme-docs/src/components/link.js
- websites/docs-smoke-test/src/content/components/cards.mdx
closes #1291 
Now cards with external links won't render the external link icon anymore. It appears only next to textlinks.
> Render cards without external link icon

- .changeset/rare-shoes-run.md
- packages/gatsby-theme-docs/gatsby-node.js
resolves #1221 (better than before)
We broke the existing error handling while adding the time to read feature.
This makes it more generic and applicable to multiple dynamically resolved fields with varying types. 
The fundamental limitation to have to restart remains because of the behavior of the MDX plugin.
> More robust MDX error handling

- .changeset/rotten-tomatoes-divide.md
- packages/gatsby-transformer-raml/src/create-type-node.js
Fixes: commercetools-docs#2051
> fix(raml transformer): hide fields with markDeprecated property from api generated docs

- .changeset/neat-kiwis-dance.md
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
- packages/gatsby-theme-docs/src/overrides/avatar.js
This pull request implements the new overridable avatar component. This is needed in order to override the component in the learning-tech websites to display the avatar (or not, if the user is not logged in yet).
> Provide component shadowing for the avatar component

- .changeset/modern-pets-type.md
- packages/writing-style/styles/commercetools/WordList-Suggestions.yml
**Info:** The words 'via' and 'once' must be avoided in documentation as per the [Google's word list](https://developers.google.com/style/word-list). Hence, this PR adds the suggestions to _commercetools/WordList-Suggestions.yml_ file.
> Adds additional terms to Vale writing style checker

- .changeset/small-jobs-work.md
- packages/gatsby-theme-docs/package.json
- packages/ui-kit/package.json
- yarn.lock
This might help reducing the bundle size.
What I did is running the `yarn up -R` command which forces a refresh of all matching dependencies to their latest allowed version. This is useful when some dependencies are defined with version ranges but there are different versions installed (you can inspect it with `yarn why`).
```
yarn up -R '@commercetools-uikit/*'
yarn up -R '@emotion/*'
yarn up -R '@babel/*'
```
> chore: refresh uikit deps, keep react-intl v5

- .changeset/friendly-colts-approve.md
- packages/gatsby-theme-docs/src/components/link.js
- websites/docs-smoke-test/src/content/views/links.mdx
I've noticed during the frontend docs migration that the link component in the kit did not support email links yet. They were rendered by gatsby as internal links which led to a wrong url.
This PR implements `mailto` links as external links which will fix the issue and make it possible to support the email links in the frontend docs content.
> [Feat] support email links and render them as external links

- .changeset/silly-rivers-swim.md
- algolia-crawler.js
- packages/gatsby-theme-docs/src/components/seo.js
closes #1444 
This pull request changes the site-context implementation in `layout-header` to have an element that Algolia can use to read the full site context as it appears in the header.
If we split the information into two elements, the crawler is not able to read out one element to get a clean string.
> Search result improvements

- .changeset/thin-pumpkins-kiss.md
- packages/gatsby-theme-docs/package.json
- packages/gatsby-theme-docs/src/components/release-notes-filter-dates.js
- packages/gatsby-theme-docs/src/components/release-notes-filter-topics.js
- yarn.lock
Follow up from the discussion here:
https://github.com/commercetools/commercetools-docs-kit/pull/1423
will close #1382 
This pull request replaces the date-input filter from the ui-kit with a new custom native html date picker.
Preview deeplink:  https://docskit-pr-1446.commercetools.vercel.app/docs-smoke-test/releases
> Replace `date-filter` ui-kit component with new custom component as release note filter

- .changeset/forty-sloths-fail.md
- packages/gatsby-theme-docs/gatsby-browser.js
- packages/gatsby-theme-docs/globals.css
- packages/gatsby-theme-docs/src/components/theme-provider.js
- packages/gatsby-theme-docs/src/layouts/content-homepage.js
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
- packages/gatsby-theme-docs/src/layouts/release-notes-detail.js
- packages/gatsby-theme-docs/src/layouts/release-notes-list.js
- packages/gatsby-theme-docs/src/templates/homepage.js
- packages/gatsby-theme-docs/src/templates/page-content.js
- packages/gatsby-theme-docs/src/templates/release-notes-detail.js
- packages/gatsby-theme-docs/src/templates/release-notes-list.js
- packages/ui-kit/src/components/globals.tsx
Temporary workaround for #1410
> refactor: load CSS variables via global import instead of using `<ThemeProvider>`

- .changeset/proud-adults-think.md
- packages/gatsby-theme-docs/gatsby-config.js
- packages/gatsby-theme-docs/package.json
- packages/gatsby-theme-docs/src/components/link.js
- packages/gatsby-theme-docs/utils/default-options.js
- websites/documentation/src/content/configuration/theme.mdx
- yarn.lock
Resolves #1469 
includes two small changes of related scope: pass identical config to hubspot tracker and do not block passing the referrer to external links so our own other sites can see what traffic comes from the docs.
> refactor: use gtag.js and support multiple IDs

- .changeset/giant-cougars-live.md
- packages/gatsby-theme-docs/src/layouts/internals/page-content-inset.js
The issue was introduced with this change that was made for the sticky example feature:
https://github.com/commercetools/commercetools-docs-kit/commit/86feac81f1127d2b5c9645147463a8d77bef33c3#diff-f1996a28d6f3f74e10c2bd9bac8c7e46a2a566b5549b06065d9f39d4e00ec1b0L19
I checked the sticky behaviour..it is still working as expected.
Please also have a look into the snapshots. They will show that not only the card borders are fixed but also all bottom-borders that we use inside of the sections.
closes #1442
> fix: card border being cut off

- .changeset/thin-coats-repeat.md
- packages/gatsby-theme-docs/package.json
- yarn.lock
Just two things that we should change :)
`gatsby-plugin-google-gtag` should have the latest v4 version because of Gatsby v4.
`cosmiconfig` should go to dev dependencies
> Simple tech maintenance

- .changeset/new-apricots-sip.md
- api-specs/test/api.raml
- api-specs/test/examples/action-success.json
- api-specs/test/examples/product-example.json
- packages/gatsby-theme-api-docs/src/components/resource/method/highlights.js
- packages/gatsby-theme-api-docs/src/components/resource/method/method.js
- packages/gatsby-theme-api-docs/src/components/resource/method/request-representation.js
- packages/gatsby-theme-api-docs/src/components/resource/method/responses.js
- packages/gatsby-theme-api-docs/src/components/resource/method/scopes.js
- packages/gatsby-theme-api-docs/src/components/resource/method/title.js
- packages/gatsby-theme-api-docs/src/hooks/use-api-resources.js
- packages/gatsby-theme-api-docs/src/utils/render-type-as-link.js
- packages/gatsby-transformer-raml/src/schema/define-raml-resource.js
- packages/gatsby-transformer-raml/src/utils/resource/do-recursion.js
- websites/api-docs-smoke-test/src/content/endpoints/endpoints-for-resource.mdx
This pull request implements requested enhancements:
- the content type is now displayed next to `body`
- the request and response bodies are were adjusted to support images
- descriptions inside of the response body are now displayed next to the response code
closes #1426
closes #1430 
closes #1324 
Link to the examples:
https://docskit-pr-1462.commercetools.vercel.app/api-docs-smoke-test/endpoints/endpoints-for-resource
Design ideas:
> [feats] Enhancements for the request body

- .changeset/lazy-laws-bake.md
- packages/gatsby-theme-docs/gatsby-config.js
- packages/gatsby-theme-docs/package.json
- yarn.lock
follow up task from this PR:
https://github.com/commercetools/commercetools-docs-kit/pull/1484
> [Gatsby plugin cleanup] Remove unused meta redirect plugin

- .changeset/long-crabs-watch.md
- packages/gatsby-theme-docs/gatsby-node.js
Since we are fully replacing the webpack config the standard approaches to disable source maps don't work, it has to be directly in our gatsby-node.js
Also, the approaches we tried optimized the JS build stage but our problem is in the HTML build stage. 
To my nonscientific observation this reduces memory usage by ca. 50%  in the docs-smoke-test on main (MDX v2 based)
> feat: reduce mem in critical stage no sourcemaps

- .changeset/quick-colts-explode.md
- cypress/e2e/docs-smoke-test/top-menu.cy.ts
- lint-staged.config.js
- packages/ui-kit/package.json
- packages/ui-kit/src/components/mermaid-client-side.tsx
- packages/ui-kit/src/components/mermaid.tsx
- packages/ui-kit/src/hooks/use-script.ts
- packages/ui-kit/src/mermaid.d.ts
- yarn.lock
@emmenko  had proposed this already in the original implementation PR, at the time I had preferred having the mermaid version and exact code controlled through NPM and renovate like all other dependencies.  But I did underestimate the impact that such large dependencies can have on the overall gatsby build and develop server through memory pressure and repetitive bundling and compression. 
So here's an approach to load the mermaid javscript client side from the jsdelivr CDN.  It's using a script loader hook someone else wrote (linked in the code).   I have the feeling there might be a simpler way  (e.g. ESM importing the library from the client side?)  but at least this one changes as little as possible and works.  
There may be inefficiencies that lead to flicker, a review would be …
> Load Mermaid JS from CDN to reduce build load

- .changeset/forty-books-begin.md
- packages/gatsby-theme-docs/gatsby-node.js
This brings the development server down to very low memory and startup time but at the cost of dev server robustness. 
That's why it's hidden behind our LOW_MEM flag which has other negative effects too (no information about where an error is, uncached builds)
> Webpack experimental lazy compilation in low_mem mode

- .github/workflows/release.yml
following their documentation, this unlocks minor
versions of the changesets action.
The 1.2 we hardwired uses the deprecated way
to set outputs and would at some point fail
> Allow newer changeset GH action versions

- packages/gatsby-theme-docs/gatsby-browser.js
- packages/gatsby-theme-docs/package.json
- yarn.lock
This removes one big bundle (sentry replay) which webpack was not able to tree-shake because of the dynamic import.
Does not need a changeset imho, will go out with whatever next release
> Statically import sentry to enable tree shake

- packages/writing-style/styles/commercetools/WordList.yml
When used as an adjective preceding a noun, open-source should be hyphenated. 
Sources:
- https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/open-source
- https://www.oxfordlearnersdictionaries.com/definition/english/open-source
I deleted the check entirely, instead of swapping them around since there can be cases when the non-hyphenated version should be used (see in Microsoft example above).
> Remove open-source from banned words

- .changeset/brave-spiders-hide.md
- packages/gatsby-theme-docs/src/components/search-input.js
> Improve `closeIcon` size and spacing in `search input`

- .changeset/tough-walls-laugh.md
- packages/ui-kit/src/components/markdown.tsx
closes #1748 
Hi @zbalek 
This is how the content page looks like if we reduce the spacing between the sections to 8px as suggested in the Figma board. I personally think that it looks a bit too squeezed now. Maybe 16px between the h3 sections would be better, but that's just my opinion :)
> [Design adjustments] Reduce spacing between sections in the content page

- .changeset/light-plums-end.md
- cypress/e2e/self-learning-smoke-test/02-profile-modal.ts
- cypress/support/step_definitions/common.steps.ts
- packages/gatsby-theme-docs/src/modules/self-learning/components/profile-modal.tsx
- packages/gatsby-theme-docs/src/modules/self-learning/components/user-profile-init.tsx
- packages/gatsby-theme-docs/src/modules/self-learning/components/verify-email-button.tsx
- packages/gatsby-theme-docs/src/modules/self-learning/hooks/use-send-verification-email.ts
- packages/gatsby-theme-docs/src/modules/sso/sso.const.ts
This PR covers the following problems and partially addresses commercetools/learning-tech#454 and part of commercetools/learning-tech#429
- Allowing a user to see their email that they logged in with.
- Allowing the user to see whether their account is verified or not and if not to resend a verification email.
- Allowing the user to see whether their company association is verified or not and instructions on how to verify it.
Still missing
- do we need to show anything else to push for email verification ? a notification message/ banner because now it is hidden inside the profile modal only
Some Screenshots how it looks like
> feat: email verification + company association

- .changeset/late-dolls-occur.md
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
Fix the issue reported in here: https://github.com/commercetools/commercetools-docs/pull/3869#issuecomment-1716345333
> fix: fix clickable items under sidebar shade

- .changeset/chilly-pillows-remain.md
- packages/ui-kit/src/components/code-block.tsx
- websites/docs-smoke-test/src/content/views/code-blocks.mdx
closes #1332
This PR is a proposal to fix a problem we have with comments in code examples when they are part of a highlighted section since currently they are not visible in that situation.
Check the first line of the following example:
**BEFORE**
**AFTER**
> Fix comments color when highlighted

- .changeset/three-jobs-greet.md
- packages/ui-kit/src/components/dialogs/internals/dialog-container.tsx
- packages/ui-kit/src/components/dialogs/internals/dialog-content.tsx
Fixes the height of the modal for `size=scale` and removes extra padding at the top and bottom.
> Adjust modal component for the chat modal

- cypress/e2e/docs-smoke-test/pagination.cy.ts
pagination e2e test was running on `components` folder which includes `images`. This page is thorwing a hydration error which is a know issue but it's not relevant for the e2e test. So I decided to run the same pagination e2e on another folder. The functionality remains the same
> chore: change pagination e2e to avoid img hydration error

- .changeset/violet-seas-train.md
- packages/gatsby-theme-docs/index.js
- packages/gatsby-theme-docs/src/components/index.js
- packages/gatsby-theme-docs/src/components/page-redirection.ts
- packages/gatsby-theme-docs/src/content/404.mdx
- websites/documentation/src/content/writing/pages.mdx
Following what suggested in the [comment](https://github.com/commercetools/commercetools-docs-kit/issues/1858#issuecomment-1803923107), I created a component `<PageRedirection>` that can be used in mdx files and essentially performs a configurable redirection after a configurable amount of time
> feat: add PageRedirection component

- .changeset/grumpy-dingos-attend.md
- packages/writing-style/styles/commercetools/Incomplete.yml
This PR extends the writing style checks for 'Incomplete' to add TBC and TO-DO.
> Add TBC, and TO-DO for incomplete writing style checks

- websites/documentation/src/content/writing/release-notes.mdx
This PR improves the definition of `orderHint` for release notes frontmatter. Docs only, no functional change.
> Improve docs for orderHint

- .changeset/odd-countries-rescue.md
- api-specs/test/api.raml
- api-specs/test/types/regex-properties-type-array.raml
- packages/gatsby-theme-api-docs/src/components/type/properties/rows/name-type.js
- websites/api-docs-smoke-test/src/content/types/general.mdx
> Display regex array type descriptions correctly

- .changeset/lazy-years-end.md
- packages/writing-style/styles/commercetools/WordList.yml
In [docs ticket #4905](https://github.com/commercetools/commercetools-docs/pull/4905) we changed all instances of ecommerce/e-commerce to commerce. This PR is to update the Vale wordlist to reflect this.
> Add 'commerce' to Vale word list

- .changeset/afraid-moose-tell.md
- packages/gatsby-theme-docs/src/layouts/internals/layout-release-note-body.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-release-note.js
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
- websites/docs-smoke-test/src/releases/release-note-with-index-frontmatters.mdx
**Fixes**
- hover colors on release notes (discussed with @zbalek )
- show the `productArea` label only if `product` has not the same value already (see connect or checkout)
> [release notes] Further adjustments that need to go into the next release

- algolia-crawler.js
**Description of changes** 
adjusted the crawler file (also in algolia) to properly crawl the subtitle of a page.
**Link original ticket** 
https://github.com/commercetools/commercetools-docs/issues/3227
**Link to test the change**
https://docs-kit.commercetools.vercel.app/docs-smoke-test/
**Screenshot of changes (if applicable)** 
> fix: bug in crawler selector to capture subtitle data while crawling

- .changeset/smart-tomatoes-flow.md
- packages/gatsby-theme-docs/src/layouts/internals/layout-header.js
Fix the color of the caret icon when the megamenu is open
Closes https://github.com/commercetools/commercetools-docs/issues/5209
** Screenshot of changes (if applicable) **
> Ga megamenu arrow

- .changeset/lazy-rice-tie.md
- cypress/e2e/self-learning-smoke-test/e2e.const.ts
- packages/gatsby-theme-docs/src/modules/self-learning/components/quiz.tsx
- packages/ui-kit/src/design-system.ts
Adjust the color of the self-learning quiz wrapper 
https://github.com/commercetools/learning-tech/issues/659
** Screenshot of changes (if applicable)
**
> chore: use correct colors for self-learning quiz wrapper

- .changeset/quick-cherries-chew.md
- packages/ui-kit/src/components/multi-code-block.tsx
- websites/docs-smoke-test/src/content/components/code-blocks.mdx
**Description of changes**
The code block component was adjusted to fix an issue with the code block language when the title of the code block is too long. We basically no longer allow line breaks for the language.
**Link original ticket**
closes #1809 
**Screenshot of changes (if applicable)**
Link to the example in the docs:
https://docskit-tt-fix-code-block-language-wrapping.commercetools.vercel.app/docs-smoke-test/components/code-blocks
> Fix: code block language wrapping

- .changeset/honest-guests-double.md
- packages/writing-style/styles/commercetools/WordList.yml
** Description of changes **: Closed Beta features would now be called Early Access features. As an extension to the primary changes made on https://github.com/commercetools/commercetools-docs/pull/5398, I have now added the 'closed beta' to the word list to minimize accidental usage of the old term.
> Adds 'closed beta' to Vale wordlist

- .changeset/serious-panthers-repeat.md
- cypress/e2e/docs-smoke-test/site-overrides.cy.ts
- packages/gatsby-theme-docs/gatsby-node.mjs
- packages/gatsby-theme-docs/src/layouts/content.js
- packages/gatsby-theme-docs/src/layouts/internals/layout-sidebar.js
- packages/gatsby-theme-docs/src/layouts/internals/self-learning/sidebar.js
- packages/gatsby-theme-docs/src/layouts/internals/sidebar.js
- websites/docs-smoke-test/src/content/views/overrides.mdx
- websites/documentation/src/content/writing/pages.mdx
Create the possibility of override the sidebar site title link href which by default links to the site root.
Closes [#5358](https://github.com/commercetools/commercetools-docs/issues/5378)
> Ga release notes title override

- websites/documentation/src/content/writing/code.mdx
Adjusts the docs for the MultiCodeBlock to show that only one title can be defined for the MultiCodeBlock
closes #1877
> [Documentation] Improve docs for the `MultiCodeBlock`

- .changeset/khaki-ghosts-know.md
- packages/gatsby-theme-docs/src/layouts/internals/layout-application.js
- websites/docs-smoke-test/src/content/views/links.mdx
Fix the normal scroll to anchor behaviour which appeared to be broken by [this PR](https://github.com/commercetools/commercetools-docs-kit/pull/2031/files).
Reverting this change will disable the [highlighting of search results in the scrollbar](https://github.com/commercetools/commercetools-docs-kit/issues/1606).
I think at the moment is better to prioritise a core functionality such as the scrolling to anchor over the highlighting of search results in the scrollbar.
Closes https://github.com/commercetools/commercetools-docs/issues/5484
The issue can be checked here:
https://docskit-ga-broken-anchor-scroll.commercetools.vercel.app/docs-smoke-test/views/links#link-to-another-page-on-this-site-with-a-specific-anchor-a-page-on-this-site …
> fix: scroll to anchor not working when navigating to a different page

- .changeset/fair-rockets-fix.md
- api-specs/test/api.raml
- packages/gatsby-theme-api-docs/src/components/resource/method/scopes.js
- packages/gatsby-theme-api-docs/src/components/resource/method/scopes.tsx
closes https://github.com/commercetools/commercetools-docs/issues/4871
** Screenshot of changes (if applicable) **
After:
Maintaining no column for less than 10 scopes and two columns for more than 10 scopes:
> Display multiple scopes in api endpoints in two columns

- .changeset/violet-turkeys-divide.md
- packages/gatsby-theme-api-docs/src/components/resource/method/scopes.tsx
**Description**
In previous PR an import path was incorrectly accessing files. We need to update the import path.
> [fix] Scopes layout patch: update import path 

- websites/documentation/src/content/writing/pages.mdx
Fix an incorrect information in the documentation site regarding site overrides in the frontmatter section of each page. Thanks @mar-gil for pointing that out
> chore: fix incorrect information in the docs

- .changeset/strange-walls-pump.md
- .github/workflows/main.yml
- packages/gatsby-theme-docs/index.js
- packages/gatsby-theme-docs/src/components/LearningObjectivesCard/LearningObjectivesCard.tsx
- packages/gatsby-theme-docs/src/components/SelfLearningContentNotification/SelfLearningContentNotification.tsx
- packages/gatsby-theme-docs/src/components/cards.js
- websites/docs-smoke-test/src/content/views/beta.mdx
- websites/self-learning-smoke-test/src/content/index.mdx
**Description of changes**
we introduce 2 new components to get rid of custom markup used in the self-learning pages which leads to hydration issues and semantic problems. This work is also useful for next docs as it allows to remove icons dependencies from the mdx
**Screenshot of changes (if applicable)**
`SelfLearningContentNotification` component
`LearningObjectivesCard` component
> feat: create utility components for self-learning purpose

- .changeset/popular-owls-clean.md
- packages/gatsby-theme-docs/index.js
- packages/gatsby-theme-docs/src/components/advanced-search-filter.tsx
- packages/gatsby-theme-docs/src/modules/self-learning/components/login-or-guest.tsx
- websites/self-learning-smoke-test/src/content/index.mdx
**Description of changes**
Add LoginOrGuest component to get rid of custom html markup in some html pages and added InStore search filter
**Link to original ticket**
**Link to change** (deep-link for reviewing the change)
**Screenshot of changes (if applicable)**
> feat: add LoginOrGuest component
